"use client";

import "./connection-settings.css";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { createConnection, getConnection, listConnections, listConnectionTypes, mapConnection, updateConnection, validateConnectionForm, type ConnectionFormInput, type ConnectionTypeDto, type ConnectionVm, type WorkflowConnectionDto } from "./workflow-connection-api";

type Drawer = { mode: "create" } | { mode: "edit"; item: WorkflowConnectionDto } | null;
const words = { connection: "执行连接", add: "添加连接", edit: "编辑", save: "保存", cancel: "取消", retry: "重试" };
const blank = (connectionType = ""): ConnectionFormInput => ({ name: "", connectionType, baseUrl: "", timeoutSeconds: 60, typeConfigJson: '{"referenceType":"workflow_id","referenceValue":""}', credential: "" });

function ConnectionDrawer({ drawer, types, onClose, onSaved }: { drawer: Exclude<Drawer, null>; types: ConnectionTypeDto[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const editing = drawer.mode === "edit";
  const initial = (): ConnectionFormInput => editing ? { name: drawer.item.name, connectionType: drawer.item.connectionType, baseUrl: drawer.item.baseUrl, timeoutSeconds: drawer.item.timeoutSeconds, typeConfigJson: JSON.stringify(drawer.item.typeConfig), credential: "" } : blank(types[0]?.connectionType);
  const [form, setForm] = useState<ConnectionFormInput>(initial);
  const [error, setError] = useState<string>(); const [conflict, setConflict] = useState(false); const [saving, setSaving] = useState(false);
  const config = (() => { try { return JSON.parse(form.typeConfigJson) as { referenceType?: string; referenceValue?: string }; } catch { return { referenceType: "workflow_id", referenceValue: "" }; } })();
  const set = <K extends keyof ConnectionFormInput>(key: K, value: ConnectionFormInput[K]) => { setForm(current => ({ ...current, [key]: value })); setError(undefined); };
  const setReference = (key: "referenceType" | "referenceValue", value: string) => set("typeConfigJson", JSON.stringify({ ...config, [key]: value }));
  const reload = async () => { if (!editing) return; setSaving(true); try { const item = await getConnection(drawer.item.id); setForm({ name: item.name, connectionType: item.connectionType, baseUrl: item.baseUrl, timeoutSeconds: item.timeoutSeconds, typeConfigJson: JSON.stringify(item.typeConfig), credential: "" }); setConflict(false); setError("已加载服务端最新配置，请确认后重新保存。"); } catch { setError("暂时无法加载最新配置。"); } finally { setSaving(false); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const invalid = validateConnectionForm(form, editing); if (invalid) { setError(invalid); return; } setSaving(true); setError(undefined); try { if (editing) await updateConnection(drawer.item.id, { name: form.name, baseUrl: form.baseUrl, timeoutSeconds: form.timeoutSeconds, typeConfigJson: form.typeConfigJson, credential: form.credential, expectedVersion: drawer.item.version }, crypto.randomUUID()); else await createConnection(form, crypto.randomUUID()); await onSaved(); onClose(); } catch (cause) { const api = cause instanceof ApiError ? cause : undefined; if (api?.status === 409 || api?.code === "version_conflict") { setConflict(true); setError("该连接已被其他操作更新，请重新加载后再保存。"); } else setError("保存失败，请检查输入后重试。"); } finally { setSaving(false); } };
  return <div className="llm-drawer-backdrop"><aside className="llm-drawer" role="dialog" aria-modal="true"><header><div><h2>{editing ? `${words.edit}${words.connection}` : words.add}</h2><p>配置通用工作流连接</p></div><button type="button" aria-label="关闭" onClick={onClose} disabled={saving}>×</button></header><form onSubmit={submit}><div className="llm-drawer-body"><label>连接名称 *<input value={form.name} maxLength={120} onChange={event => set("name", event.target.value)} disabled={saving} /></label><label>连接类型 *<select value={form.connectionType} onChange={event => set("connectionType", event.target.value)} disabled={editing || saving}>{types.map(type => <option key={type.connectionType} value={type.connectionType}>{type.displayName}</option>)}</select>{editing && <small>连接类型创建后不可修改。</small>}</label><label>Base URL *<input type="url" value={form.baseUrl} onChange={event => set("baseUrl", event.target.value)} disabled={saving} /></label><label>API Key{editing ? "" : " *"}<input type="password" value={form.credential} autoComplete="new-password" onChange={event => set("credential", event.target.value)} disabled={saving} /><small>{editing && drawer.item.hasCredential ? "已配置；留空将保留原凭证。" : "凭证加密保存，不会回显。"}</small></label><label>请求超时（秒）<input type="number" min="5" max="300" value={form.timeoutSeconds} onChange={event => set("timeoutSeconds", Number(event.target.value))} disabled={saving} /></label><label>引用类型 *<select value={config.referenceType} onChange={event => setReference("referenceType", event.target.value)} disabled={saving}><option value="workflow_id">Workflow ID</option><option value="webhook_path">Webhook Path</option></select></label><label>引用值 *<input value={config.referenceValue} maxLength={512} onChange={event => setReference("referenceValue", event.target.value)} disabled={saving} /></label><div className="llm-deferred"><button type="button" disabled>验证连接（后续开放）</button><p>本迭代不会连接 n8n 或其他第三方系统。</p></div>{error && <div className="llm-form-error" role="alert">{error}{conflict && <button type="button" onClick={() => void reload()} disabled={saving}>重新加载</button>}</div>}</div><footer><button type="button" onClick={onClose} disabled={saving}>{words.cancel}</button><button className="primary" disabled={saving}>{saving ? "保存中…" : words.save}</button></footer></form></aside></div>;
}

export function ConnectionSettingsPage() {
  const [types, setTypes] = useState<ConnectionTypeDto[] | null>(null); const [items, setItems] = useState<ConnectionVm[] | null>(null); const [total, setTotal] = useState(0); const [error, setError] = useState<string>(); const [drawer, setDrawer] = useState<Drawer>(null); const [notice, setNotice] = useState<string>();
  const [query, setQuery] = useState(""); const [type, setType] = useState(""); const [status, setStatus] = useState(""); const [enabled, setEnabled] = useState(""); const [offset, setOffset] = useState(0); const limit = 20;
  const load = useCallback(async (signal?: AbortSignal) => { setError(undefined); try { const [catalogue, result] = await Promise.all([listConnectionTypes({ signal }), listConnections({ q: query, connectionType: type || undefined, integrationStatus: status === "not_connected" ? "not_connected" : undefined, enabled: enabled === "true" ? true : enabled === "false" ? false : undefined, limit, offset }, { signal })]); setTypes(catalogue.items); setItems(result.items.map(item => mapConnection(item, catalogue.items))); setTotal(result.total); } catch (cause) { if (!(cause instanceof ApiError && cause.code === "cancelled")) setError("暂时无法加载执行连接，请稍后重试。"); } }, [enabled, offset, query, status, type]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => void load(controller.signal), 300); return () => { window.clearTimeout(timer); controller.abort(); }; }, [load]);
  const resetPage = (action: () => void) => { setOffset(0); action(); };
  const edit = async (item: ConnectionVm) => { try { setDrawer({ mode: "edit", item: await getConnection(item.id) }); } catch { setNotice("暂时无法读取连接详情。"); } };
  const page = Math.floor(offset / limit) + 1; const pages = Math.max(1, Math.ceil(total / limit));
  return <section className="settings-content"><section className="llm-content-card"><header><div><h2>{words.connection}</h2><p>管理可供工作流使用的执行连接</p></div><button className="primary" onClick={() => setDrawer({ mode: "create" })} disabled={!types?.length}>{words.add}</button></header>{notice && <p className="llm-toast" role="status">{notice}</p>}{error ? <div className="llm-state" role="alert"><h3>暂时无法加载</h3><p>{error}</p><button onClick={() => void load()}>{words.retry}</button></div> : !types || !items ? <div className="llm-loading" role="status">正在加载执行连接…</div> : items.length === 0 ? <div className="llm-state"><h3>暂无执行连接</h3><p>添加连接后，可供后续工作流配置使用。</p></div> : <><div className="llm-toolbar"><input value={query} onChange={event => resetPage(() => setQuery(event.target.value))} placeholder="搜索连接名称" /><select value={type} onChange={event => resetPage(() => setType(event.target.value))}><option value="">全部类型</option>{types.map(item => <option key={item.connectionType} value={item.connectionType}>{item.displayName}</option>)}</select><select value={status} onChange={event => resetPage(() => setStatus(event.target.value))}><option value="">全部集成状态</option><option value="not_connected">未接入</option></select><select value={enabled} onChange={event => resetPage(() => setEnabled(event.target.value))}><option value="">全部启用状态</option><option value="false">未启用</option><option value="true">已启用</option></select><span>共 {total} 个连接</span></div><div className="llm-table-wrap"><table><thead><tr><th>连接名称</th><th>连接类型</th><th>Base URL</th><th>引用类型</th><th>集成状态</th><th>操作</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.name}</strong>{item.hasCredential && <small>凭证已配置{item.credentialFingerprint && ` · ${item.credentialFingerprint}`}</small>}</td><td>{item.typeLabel}</td><td className="llm-url">{item.baseUrl}</td><td>{item.referenceLabel}</td><td><span className="llm-status">{item.statusLabel}</span></td><td><button onClick={() => void edit(item)}>{words.edit}</button></td></tr>)}</tbody></table></div><div className="llm-pagination"><span>第 {page} / {pages} 页</span><button disabled={offset === 0} onClick={() => setOffset(current => Math.max(0, current - limit))}>上一页</button><button disabled={offset + limit >= total} onClick={() => setOffset(current => current + limit)}>下一页</button></div></>}</section>{drawer && types && <ConnectionDrawer drawer={drawer} types={types} onClose={() => setDrawer(null)} onSaved={async () => { await load(); setNotice("连接已保存，并已同步服务端最新数据。"); }} />}</section>;
}
