"use client";

import "./connection-settings.css";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { createConnection, getConnection, listConnections, listConnectionTypes, mapConnection, setConnectionEnabled, updateConnection, validateConnectionForm, verifyConnection, type ConnectionFormInput, type ConnectionTypeDto, type ConnectionVm, type WorkflowConnectionDto } from "./workflow-connection-api";

type Drawer = { mode: "create" } | { mode: "edit"; item: WorkflowConnectionDto } | null;
const blank = (connectionType = ""): ConnectionFormInput => ({ name: "", connectionType, baseUrl: "", timeoutSeconds: 60, typeConfigJson: '{"referenceType":"workflow_id","referenceValue":""}', credential: "" });

function ConnectionDrawer({ drawer, types, onClose, onSaved }: { drawer: Exclude<Drawer, null>; types: ConnectionTypeDto[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const editing = drawer.mode === "edit";
  const [form, setForm] = useState<ConnectionFormInput>(() => editing ? { name: drawer.item.name, connectionType: drawer.item.connectionType, baseUrl: drawer.item.baseUrl, timeoutSeconds: drawer.item.timeoutSeconds, typeConfigJson: JSON.stringify(drawer.item.typeConfig), credential: "" } : blank(types[0]?.connectionType));
  const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const set = <K extends keyof ConnectionFormInput>(key: K, value: ConnectionFormInput[K]) => setForm(current => ({ ...current, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); const invalid = validateConnectionForm(form, editing); if (invalid) return setMessage(invalid); setBusy(true); try { if (editing) await updateConnection(drawer.item.id, { ...form, expectedVersion: drawer.item.version }, crypto.randomUUID()); else await createConnection(form, crypto.randomUUID()); await onSaved(); onClose(); } catch (cause) { setMessage(cause instanceof ApiError && cause.status === 409 ? "Configuration changed. Reload and try again." : "Save failed. Please try again."); } finally { setBusy(false); } };
  const command = async (enabled?: boolean) => { if (!editing || busy) return; setBusy(true); try { if (enabled === undefined) await verifyConnection(drawer.item.id, drawer.item.version, crypto.randomUUID()); else await setConnectionEnabled(drawer.item.id, drawer.item.version, enabled, crypto.randomUUID()); await onSaved(); setMessage("Latest status has been refreshed."); } catch (cause) { setMessage(cause instanceof ApiError && cause.status === 409 ? "Configuration changed. Reload and try again." : "Action failed. Please try again."); } finally { setBusy(false); } };
  const config = (() => { try { return JSON.parse(form.typeConfigJson) as { referenceType: "workflow_id" | "webhook_path"; referenceValue: string }; } catch { return { referenceType: "workflow_id" as const, referenceValue: "" }; } })();
  const setConfig = (key: "referenceType" | "referenceValue", value: string) => set("typeConfigJson", JSON.stringify({ ...config, [key]: value }));
  return <div className="llm-drawer-backdrop"><aside className="llm-drawer" role="dialog" aria-modal="true" aria-label={editing ? "Edit workflow connection" : "Add workflow connection"}><header><div><h2>{editing ? "Edit connection" : "Add connection"}</h2><p>Credentials are input-only and never returned to this page.</p></div><button type="button" aria-label="Close" onClick={onClose} disabled={busy}>×</button></header><form onSubmit={save}><div className="llm-drawer-body"><label>Name *<input value={form.name} maxLength={120} onChange={event => set("name", event.target.value)} disabled={busy}/></label><label>Type *<select value={form.connectionType} onChange={event => set("connectionType", event.target.value)} disabled={editing || busy}>{types.map(type => <option key={type.connectionType} value={type.connectionType}>{type.displayName}</option>)}</select></label><label>Base URL *<input type="url" value={form.baseUrl} onChange={event => set("baseUrl", event.target.value)} disabled={busy}/></label><label>API Key{editing ? "" : " *"}<input type="password" value={form.credential} autoComplete="new-password" onChange={event => set("credential", event.target.value)} disabled={busy}/><small>{editing && drawer.item.hasCredential ? "Saved; leaving blank retains it." : "Stored securely and never shown again."}</small></label><label>Timeout (seconds)<input type="number" min="5" max="300" value={form.timeoutSeconds} onChange={event => set("timeoutSeconds", Number(event.target.value))} disabled={busy}/></label><label>Reference type<select value={config.referenceType} onChange={event => setConfig("referenceType", event.target.value)} disabled={busy}><option value="workflow_id">Workflow ID</option><option value="webhook_path">Webhook path</option></select></label><label>Reference value *<input value={config.referenceValue} maxLength={512} onChange={event => setConfig("referenceValue", event.target.value)} disabled={busy}/></label>{editing && <div className="llm-deferred"><button type="button" disabled={busy} onClick={() => void command()}>Verify connection</button><button type="button" disabled={busy} onClick={() => void command(!drawer.item.enabled)}>{drawer.item.enabled ? "Disable" : "Enable"}</button><p>Save, verification, and enablement are separate actions.</p></div>}{message && <div className="llm-form-error" role="alert">{message}</div>}</div><footer><button type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving…" : "Save"}</button></footer></form></aside></div>;
}

export function ConnectionSettingsPage() {
  const [types, setTypes] = useState<ConnectionTypeDto[] | null>(null); const [items, setItems] = useState<ConnectionVm[] | null>(null); const [total, setTotal] = useState(0); const [error, setError] = useState<string>(); const [drawer, setDrawer] = useState<Drawer>(null); const [query, setQuery] = useState(""); const [validationStatus, setValidationStatus] = useState(""); const [enabled, setEnabled] = useState(""); const [offset, setOffset] = useState(0); const limit = 20;
  const load = useCallback(async (signal?: AbortSignal) => { setError(undefined); try { const [catalogue, result] = await Promise.all([listConnectionTypes({ signal }), listConnections({ q: query, validationStatus: validationStatus as "" | "unverified" | "verified" | "failed" | "stale" || undefined, enabled: enabled === "true" ? true : enabled === "false" ? false : undefined, limit, offset }, { signal })]); if (!signal?.aborted) { setTypes(catalogue.items); setItems(result.items.map(item => mapConnection(item, catalogue.items))); setTotal(result.total); } } catch (cause) { if (!(cause instanceof ApiError && cause.code === "cancelled")) setError("Unable to load connections."); } }, [enabled, offset, query, validationStatus]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => void load(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort(); }; }, [load]);
  const edit = async (item: ConnectionVm) => { try { setDrawer({ mode: "edit", item: await getConnection(item.id) }); } catch { setError("Unable to load this connection."); } };
  return <section className="settings-content"><section className="llm-content-card"><header><div><h2>Workflow connections</h2><p>Manage reusable execution connections.</p></div><button className="primary" onClick={() => setDrawer({ mode: "create" })} disabled={!types?.length}>Add connection</button></header>{error ? <div className="llm-state" role="alert"><p>{error}</p><button onClick={() => void load()}>Retry</button></div> : !items || !types ? <div className="llm-loading" role="status">Loading connections…</div> : <><div className="llm-toolbar"><input value={query} onChange={event => { setOffset(0); setQuery(event.target.value); }} placeholder="Search connections"/><select value={validationStatus} onChange={event => { setOffset(0); setValidationStatus(event.target.value); }}><option value="">All validation states</option><option value="unverified">Unverified</option><option value="verified">Verified</option><option value="failed">Failed</option><option value="stale">Stale</option></select><select value={enabled} onChange={event => { setOffset(0); setEnabled(event.target.value); }}><option value="">All enablement states</option><option value="true">Enabled</option><option value="false">Disabled</option></select><span>{total} connections</span></div>{items.length === 0 ? <div className="llm-state"><h3>No connections</h3><p>Add a connection before creating a workflow configuration.</p></div> : <div className="llm-table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Validation</th><th>Eligibility</th><th>Impact</th><th>Action</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.name}</strong>{item.hasCredential && <small>Credential saved</small>}</td><td>{item.typeLabel}</td><td>{item.validationLabel}</td><td>{item.executable ? "Executable" : item.safeError ?? "Not executable"}</td><td>{item.impactCount}</td><td><button onClick={() => void edit(item)}>Edit</button></td></tr>)}</tbody></table></div>}<div className="llm-pagination"><button disabled={offset === 0} onClick={() => setOffset(value => Math.max(0, value - limit))}>Previous</button><span>{Math.floor(offset / limit) + 1}</span><button disabled={offset + limit >= total} onClick={() => setOffset(value => value + limit)}>Next</button></div></>}</section>{drawer && types && <ConnectionDrawer drawer={drawer} types={types} onClose={() => setDrawer(null)} onSaved={load}/>}</section>;
}
