"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { create, get, list, listTypes, map, update, validate, type Form, type Platform, type PlatformType } from "./distribution-api";

type Drawer = { mode: "create" } | { mode: "edit"; platform: Platform } | null;
const empty = (platformType = ""): Form => ({ name: "", platformType, accountIdentifier: "", endpointUrl: "", authType: "api_key", timeoutSeconds: 30, typeConfigJson: "{}", note: "", credential: "" });

function PlatformDrawer({ drawer, types, onClose, onSaved }: { drawer: Exclude<Drawer, null>; types: PlatformType[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const editing = drawer.mode === "edit"; const [form, setForm] = useState<Form>(() => editing ? { name: drawer.platform.name, platformType: drawer.platform.platformType, accountIdentifier: drawer.platform.accountIdentifier, endpointUrl: drawer.platform.endpointUrl ?? "", authType: drawer.platform.authType, timeoutSeconds: drawer.platform.timeoutSeconds, typeConfigJson: JSON.stringify(drawer.platform.typeConfig, null, 2), note: drawer.platform.note ?? "", credential: "" } : empty(types[0]?.platformType)); const [error, setError] = useState<string>(); const [conflict, setConflict] = useState(false); const [saving, setSaving] = useState(false);
  const set = <K extends keyof Form>(key: K, value: Form[K]) => { setForm(current => ({ ...current, [key]: value })); setError(undefined); };
  const reload = async () => { if (!editing) return; setSaving(true); try { const x = await get(drawer.platform.id); setForm({ name: x.name, platformType: x.platformType, accountIdentifier: x.accountIdentifier, endpointUrl: x.endpointUrl ?? "", authType: x.authType, timeoutSeconds: x.timeoutSeconds, typeConfigJson: JSON.stringify(x.typeConfig, null, 2), note: x.note ?? "", credential: "" }); setConflict(false); setError("已重新加载服务端最新数据，请确认后重新保存。"); } catch { setError("暂时无法加载最新平台配置。"); } finally { setSaving(false); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const invalid = validate(form, editing); if (invalid) { setError(invalid); return; } setSaving(true); setError(undefined); try { if (editing) await update(drawer.platform.id, form, drawer.platform.version, crypto.randomUUID()); else await create(form, crypto.randomUUID()); await onSaved(); onClose(); } catch (cause) { const api = cause instanceof ApiError ? cause : undefined; if (api?.status === 409 || api?.code === "version_conflict") { setConflict(true); setError("该平台配置已被其他操作更新，请重新加载后再保存。"); } else setError("保存失败，请检查输入后重试。"); } finally { setSaving(false); } };
  return <div className="llm-drawer-backdrop"><aside className="llm-drawer" role="dialog" aria-modal="true"><header><div><h2>{editing ? "编辑分发平台配置" : "添加分发平台配置"}</h2><p>凭证加密保存；本迭代不会连接或发布到第三方平台。</p></div><button type="button" aria-label="关闭" onClick={onClose} disabled={saving}>×</button></header><form onSubmit={submit}><div className="llm-drawer-body"><label>名称 *<input value={form.name} maxLength={120} onChange={event => set("name", event.target.value)} disabled={saving} /></label><label>平台类型 *<select value={form.platformType} onChange={event => set("platformType", event.target.value)} disabled={editing || saving}>{types.map(type => <option key={type.platformType} value={type.platformType}>{type.displayName}</option>)}</select>{editing && <small>平台类型创建后不可修改。</small>}</label><label>账号标识 *<input value={form.accountIdentifier} onChange={event => set("accountIdentifier", event.target.value)} disabled={saving} /></label><label>凭证{editing ? "" : " *"}<input type="password" value={form.credential} autoComplete="new-password" onChange={event => set("credential", event.target.value)} disabled={saving} /><small>{editing && drawer.platform.hasCredential ? "已配置；留空将保留原凭证。" : "凭证加密保存，不会回显。"}</small></label><label>类型配置 (JSON) *<textarea value={form.typeConfigJson} onChange={event => set("typeConfigJson", event.target.value)} disabled={saving} /></label><label>备注<textarea value={form.note} onChange={event => set("note", event.target.value)} disabled={saving} /></label>{error && <div className="llm-form-error" role="alert">{error}{conflict && <button type="button" onClick={() => void reload()} disabled={saving}>重新加载</button>}</div>}</div><footer><button type="button" onClick={onClose} disabled={saving}>取消</button><button className="primary" disabled={saving}>{saving ? "保存中…" : "保存"}</button></footer></form></aside></div>;
}

export function DistributionSettingsPage() {
  const [types, setTypes] = useState<PlatformType[] | null>(null); const [items, setItems] = useState<ReturnType<typeof map>[] | null>(null); const [drawer, setDrawer] = useState<Drawer>(null); const [error, setError] = useState<string>();
  const load = useCallback(async (signal?: AbortSignal) => { setError(undefined); try { const [typeResult, platformResult] = await Promise.all([listTypes({ signal }), list({ signal })]); setTypes(typeResult.items); setItems(platformResult.items.map(item => map(item, typeResult.items))); } catch (cause) { if (!(cause instanceof ApiError && cause.code === "cancelled")) setError("暂时无法加载分发平台配置，请稍后重试。"); } }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const openEdit = async (platform: ReturnType<typeof map>) => { try { setDrawer({ mode: "edit", platform: await get(platform.id) }); } catch { setError("暂时无法读取平台配置详情，请重试。"); } };
  return <main className="llm-settings"><header className="llm-page-heading"><p>设置</p><h1>全局设置</h1></header><nav className="llm-tabs"><Link href="/settings">LLM 配置</Link><Link href="/settings?tab=connections">工作流配置</Link><button className="active">分发平台配置</button></nav><section className="llm-content-card"><header><div><h2>分发平台配置</h2><p>管理内容分发所需的安全配置。</p></div><button className="primary" onClick={() => setDrawer({ mode: "create" })} disabled={!types?.length}>添加分发平台配置</button></header>{error ? <div className="llm-state" role="alert"><h3>暂时无法加载</h3><p>{error}</p><button onClick={() => void load()}>重试</button></div> : !items || !types ? <div className="llm-loading" role="status">正在加载分发平台配置…</div> : items.length ? <div className="llm-table-wrap"><table><thead><tr><th>配置名称</th><th>平台类型</th><th>账号标识</th><th>凭证</th><th>集成状态</th><th>操作</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.type}</td><td>{item.account}</td><td>{item.hasCredential ? `已配置 · ${item.fingerprint ?? ""}` : "未配置"}</td><td><span className="llm-status">{item.status}</span></td><td><button onClick={() => void openEdit(item)}>编辑</button></td></tr>)}</tbody></table></div> : <div className="llm-state"><h3>暂无分发平台配置</h3><p>添加平台配置后，可供后续发布流程使用。</p></div>}</section>{drawer && types && <PlatformDrawer drawer={drawer} types={types} onClose={() => setDrawer(null)} onSaved={load} />}</main>;
}
