import { apiRequest, type ApiRequestInit } from "../../lib/api.ts";

export type FieldSchema={name:string;label:string;valueType:"string"|"integer"|"boolean"|"object";required:boolean;constraints?:Record<string,unknown>};
export type Platform={id:string;name:string;platformType:string;accountIdentifier:string;endpointUrl:string|null;authType:string;timeoutSeconds:number;typeConfig:Record<string,unknown>;note:string|null;hasCredential:boolean;credentialFingerprint:string|null;integrationStatus:"not_connected";enabled:boolean;version:number};
export type PlatformType={platformType:string;displayName:string;authTypes:string[];fieldSchemas:FieldSchema[]};
export type Form={name:string;platformType:string;accountIdentifier:string;endpointUrl:string;authType:string;timeoutSeconds:number;typeConfig:Record<string,unknown>;note:string;credential:string};
export type PlatformListQuery={q?:string;platformType?:string;integrationStatus?:"not_connected";enabled?:boolean;limit?:number;offset?:number};
const isObject=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&!Array.isArray(value)&&typeof value==="object";
export const map=(item:Platform,types:PlatformType[])=>({id:item.id,name:item.name,type:types.find(type=>type.platformType===item.platformType)?.displayName??"未知平台",account:item.accountIdentifier,hasCredential:item.hasCredential,fingerprint:item.credentialFingerprint,status:"未接入",version:item.version});
export function validate(form:Form,editing:boolean,selected?:PlatformType){if(!form.name.trim()||!form.platformType||!form.accountIdentifier.trim())return "请填写必填字段。"; if(!selected?.authTypes.includes(form.authType))return "请选择当前平台支持的认证方式。"; if(form.platformType==="custom"){try{const url=new URL(form.endpointUrl);if(url.username||url.password)throw new Error();}catch{return "自定义平台需要有效且不含用户信息的连接地址。";}}else if(form.endpointUrl){try{const url=new URL(form.endpointUrl);if(url.username||url.password)throw new Error();}catch{return "请输入有效且不含用户信息的连接地址。";}} if(!Number.isInteger(form.timeoutSeconds)||form.timeoutSeconds<5||form.timeoutSeconds>300)return "请求超时需为 5 至 300 秒之间的整数。"; for(const schema of selected?.fieldSchemas??[]){const value=form.typeConfig[schema.name];if(schema.required&&(value===undefined||value===null||value===""))return `请填写${schema.label}。`;if(schema.valueType==="integer"&&value!==undefined&&(!Number.isInteger(value)))return `${schema.label}必须是整数。`;if(schema.valueType==="object"&&value!==undefined&&!isObject(value))return `${schema.label}必须是对象。`;} if(!editing&&!form.credential.trim())return "请输入凭证。";}
const body=(form:Form)=>({name:form.name.trim(),platformType:form.platformType,accountIdentifier:form.accountIdentifier.trim(),endpointUrl:form.endpointUrl.trim()||null,authType:form.authType,timeoutSeconds:form.timeoutSeconds,typeConfig:form.typeConfig,note:form.note.trim()||null,...(form.credential.trim()?{credential:form.credential}:{})});
export const createPayload=body; export const updatePayload=(form:Form,version:number)=>{const value=body(form);return{expectedVersion:version,name:value.name,accountIdentifier:value.accountIdentifier,endpointUrl:value.endpointUrl,authType:value.authType,timeoutSeconds:value.timeoutSeconds,typeConfig:value.typeConfig,note:value.note,...(value.credential?{credential:value.credential}:{})};};
const headers=(key:string)=>({"Content-Type":"application/json","Idempotency-Key":key});
export const listTypes=(init?:ApiRequestInit)=>apiRequest<{items:PlatformType[]}>("/distribution-platform-types",init);
export const list=(query:PlatformListQuery={},init?:ApiRequestInit)=>{const params=new URLSearchParams({limit:String(query.limit??20),offset:String(query.offset??0)});if(query.q?.trim())params.set("q",query.q.trim());if(query.platformType)params.set("platformType",query.platformType);if(query.integrationStatus)params.set("integrationStatus",query.integrationStatus);if(query.enabled!==undefined)params.set("enabled",String(query.enabled));return apiRequest<{items:Platform[];total:number;limit:number;offset:number}>(`/distribution-platforms?${params}`,init);};
export const get=(id:string,init?:ApiRequestInit)=>apiRequest<Platform>(`/distribution-platforms/${encodeURIComponent(id)}`,init);
export const create=(form:Form,key:string)=>apiRequest<Platform>("/distribution-platforms",{method:"POST",headers:headers(key),body:JSON.stringify(body(form))});
export const update=(id:string,form:Form,version:number,key:string)=>apiRequest<Platform>(`/distribution-platforms/${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(key),body:JSON.stringify(updatePayload(form,version))});
