import { apiRequest, type ApiRequestInit } from "../../lib/api.ts";

export type LlmProviderType = "openai_compatible";
export type IntegrationStatus = "not_connected" | "connected" | "unverified" | "verified" | "failed";
export type ValidationStatus = "unverified" | "verifying" | "verified" | "failed" | "stale";
export type SafeError = { code: string; message: string; details?: { correlationId?: string | null; retryable?: boolean; upstreamStatusClass?: "client_error" | "server_error" | null } };
export type ValidationCheck = { code: string; status: "passed" | "warning" | "blocked"; message: string; repairAction?: string };
export type LlmProviderDto = { id: string; name: string; providerType: LlmProviderType; baseUrl: string; defaultModel: string; timeoutSeconds: number; hasSecret: boolean; secretFingerprint: string | null; integrationStatus: IntegrationStatus; validationStatus?: ValidationStatus; enabled: boolean; executable?: boolean; safeError?: SafeError | null; modelCount?: number; verifiedVersion?: number | null; checkedAt?: string | null; checks?: ValidationCheck[]; lastVerifiedAt: string | null; lastErrorCode: string | null; lastErrorMessage: string | null; version: number; createdAt: string; updatedAt: string };
export type LlmProviderTypeDto = { providerType: LlmProviderType; displayName: string; supportsSecret: boolean; fieldSchemas: unknown[] };
export type LlmProviderListDto = { items: LlmProviderDto[]; total: number; limit: number; offset: number };
export type LlmProviderVm = { id: string; name: string; providerTypeLabel: string; baseUrl: string; defaultModel: string; timeoutSeconds: number; hasSecret: boolean; secretFingerprint: string | null; integrationStatusLabel: string; validationStatusLabel: string; enabledLabel: string; executable: boolean; safeError: string | null; modelCount: number; version: number; validationStatus: ValidationStatus; enabled: boolean; lastVerifiedAt: string | null; checkedAt: string | null; lastErrorMessage: string | null };
export type ProviderFormInput = { name: string; providerType: LlmProviderType; baseUrl: string; defaultModel: string; timeoutSeconds: number; secret: string };

const providerTypeLabel: Record<LlmProviderType, string> = { openai_compatible: "OpenAI-compatible" };
const validationStatusLabel: Record<ValidationStatus, string> = { unverified: "未验证", verifying: "验证中", verified: "验证成功", failed: "验证失败", stale: "配置已变更" };
const integrationStatusLabel: Record<IntegrationStatus, string> = { not_connected: "未接入", connected: "已接入", unverified: "未验证", verified: "已验证", failed: "验证失败" };

export const mapLlmProvider = (item: LlmProviderDto): LlmProviderVm => ({ id: item.id, name: item.name, providerTypeLabel: providerTypeLabel[item.providerType] ?? "未知服务类型", baseUrl: item.baseUrl, defaultModel: item.defaultModel, timeoutSeconds: item.timeoutSeconds, hasSecret: item.hasSecret, secretFingerprint: item.secretFingerprint, integrationStatusLabel: integrationStatusLabel[item.integrationStatus] ?? "状态待确认", validationStatusLabel: item.validationStatus ? validationStatusLabel[item.validationStatus] : "未验证", enabledLabel: item.enabled ? "已启用" : "未启用", executable: item.executable === true, safeError: item.safeError?.message ?? null, modelCount: Number.isFinite(item.modelCount) ? Math.max(0, item.modelCount ?? 0) : 0, version: item.version, validationStatus: item.validationStatus ?? "unverified", enabled: item.enabled, lastVerifiedAt: item.lastVerifiedAt, checkedAt: item.checkedAt ?? null, lastErrorMessage: item.lastErrorMessage });
export const createLlmProviderPayload = (input: ProviderFormInput) => ({ name: input.name.trim(), providerType: input.providerType, baseUrl: input.baseUrl.trim(), defaultModel: input.defaultModel.trim(), timeoutSeconds: input.timeoutSeconds, ...(input.secret.trim() ? { secret: input.secret } : {}) });
export const updateLlmProviderPayload = (input: Omit<ProviderFormInput, "providerType"> & { expectedVersion: number }) => ({ expectedVersion: input.expectedVersion, name: input.name.trim(), baseUrl: input.baseUrl.trim(), defaultModel: input.defaultModel.trim(), timeoutSeconds: input.timeoutSeconds, ...(input.secret.trim() ? { secret: input.secret } : {}) });

const writeHeaders = (idempotencyKey: string) => ({ "Content-Type": "application/json", "Idempotency-Key": idempotencyKey });
export function listLlmProviderTypes(init?: ApiRequestInit) { return apiRequest<{ items: LlmProviderTypeDto[] }>("/llm-provider-types", init); }
export type LlmProviderListQuery = { q?: string; providerType?: LlmProviderType; integrationStatus?: IntegrationStatus; validationStatus?: ValidationStatus; enabled?: boolean; executable?: boolean; limit?: number; offset?: number };
export function listLlmProviders(query: LlmProviderListQuery = {}, init?: ApiRequestInit) { const params = new URLSearchParams({ limit: String(query.limit ?? 20), offset: String(query.offset ?? 0) }); if (query.q?.trim()) params.set("q", query.q.trim()); if (query.providerType) params.set("providerType", query.providerType); if (query.integrationStatus) params.set("integrationStatus", query.integrationStatus); if (query.validationStatus) params.set("validationStatus", query.validationStatus); if (query.enabled !== undefined) params.set("enabled", String(query.enabled)); if (query.executable !== undefined) params.set("executable", String(query.executable)); return apiRequest<LlmProviderListDto>(`/llm-providers?${params}`, init); }
export function getLlmProvider(providerId: string, init?: ApiRequestInit) { return apiRequest<LlmProviderDto>(`/llm-providers/${encodeURIComponent(providerId)}`, init); }
export function createLlmProvider(input: ProviderFormInput, idempotencyKey: string, init?: ApiRequestInit) { return apiRequest<LlmProviderDto>("/llm-providers", { ...init, method: "POST", headers: writeHeaders(idempotencyKey), body: JSON.stringify(createLlmProviderPayload(input)) }); }
export function updateLlmProvider(providerId: string, input: Omit<ProviderFormInput, "providerType"> & { expectedVersion: number }, idempotencyKey: string, init?: ApiRequestInit) { return apiRequest<LlmProviderDto>(`/llm-providers/${encodeURIComponent(providerId)}`, { ...init, method: "PATCH", headers: writeHeaders(idempotencyKey), body: JSON.stringify(updateLlmProviderPayload(input)) }); }
export const verifyLlmProvider = (id: string, expectedVersion: number, key: string, optionalModel?: string) => apiRequest<{ validationStatus: ValidationStatus; executable: boolean; safeError: SafeError | null; checks: ValidationCheck[] }>(`/llm-providers/${encodeURIComponent(id)}/verify`, { method: "POST", headers: writeHeaders(key), body: JSON.stringify({ expectedVersion, ...(optionalModel?.trim() ? { optionalModel: optionalModel.trim() } : {}) }) });
export const setLlmProviderEnabled = (id: string, expectedVersion: number, enabled: boolean, key: string) => apiRequest<LlmProviderDto>(`/llm-providers/${encodeURIComponent(id)}/${enabled ? "enable" : "disable"}`, { method: "POST", headers: writeHeaders(key), body: JSON.stringify({ expectedVersion }) });
export const discoverLlmProviderModels = (id: string, expectedVersion: number, key: string) => apiRequest<{ items: Array<{ modelName: string; displayName: string; available: boolean }>; total: number }>(`/llm-providers/${encodeURIComponent(id)}/models/discover`, { method: "POST", headers: writeHeaders(key), body: JSON.stringify({ expectedVersion }) });
export function validateProviderForm(input: ProviderFormInput, requiresSecret: boolean, editing: boolean) { if (!input.name.trim()) return "请输入配置名称。"; if (input.name.trim().length > 120) return "配置名称不能超过 120 个字符。"; try { new URL(input.baseUrl.trim()); } catch { return "请输入有效的 Base URL。"; } if (!input.defaultModel.trim()) return "请输入默认模型。"; if (input.defaultModel.trim().length > 160) return "默认模型不能超过 160 个字符。"; if (!Number.isInteger(input.timeoutSeconds) || input.timeoutSeconds < 5 || input.timeoutSeconds > 300) return "请求超时需为 5 至 300 秒之间的整数。"; if (requiresSecret && !editing && !input.secret.trim()) return "请输入 API Key。"; return undefined; }
