"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { listConnections, type WorkflowConnectionDto } from "./workflow-connection-api";
import { createWorkflow, getWorkflow, listWorkflows, mapWorkflow, updateWorkflow, validateWorkflow, type WorkflowDto, type WorkflowForm } from "./workflow-api";

type DrawerState = { mode: "create" } | { mode: "edit"; workflow: WorkflowDto } | null;
const blankForm = (connectionId = ""): WorkflowForm => ({ name: "", connectionId, applicableStages: ["review"], typeConfigJson: '{"referenceType":"workflow_id","referenceValue":""}', inputContractVersion: "v1", outputContractVersion: "v1", defaultParametersJson: "{}", note: "" });

function WorkflowDrawer({ state, connections, onClose, onSaved }: { state: Exclude<DrawerState, null>; connections: WorkflowConnectionDto[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const editing = state.mode === "edit";
  const [form, setForm] = useState<WorkflowForm>(() => editing ? { name: state.workflow.name, connectionId: state.workflow.connectionId, applicableStages: state.workflow.applicableStages, typeConfigJson: JSON.stringify(state.workflow.typeConfig, null, 2), inputContractVersion: state.workflow.inputContractVersion, outputContractVersion: state.workflow.outputContractVersion, defaultParametersJson: JSON.stringify(state.workflow.defaultParameters, null, 2), note: state.workflow.note ?? "" } : blankForm(connections[0]?.id));
  const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false);
  const update = <K extends keyof WorkflowForm>(key: K, value: WorkflowForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const invalid = validateWorkflow(form); if (invalid) { setError(invalid); return; } setSaving(true); try { if (editing) await updateWorkflow(state.workflow.id, form, state.workflow.version, crypto.randomUUID()); else await createWorkflow(form, crypto.randomUUID()); await onSaved(); onClose(); } catch (cause) { setError(cause instanceof ApiError && cause.status === 409 ? "\u6570\u636e\u5df2\u53d8\u5316\uff0c\u8bf7\u91cd\u65b0\u52a0\u8f7d\u540e\u4fdd\u5b58\u3002" : "\u4fdd\u5b58\u5931\u8d25\uff0c\u8bf7\u91cd\u8bd5\u3002"); } finally { setSaving(false); } };
  return <div className="llm-drawer-backdrop"><aside className="llm-drawer"><form onSubmit={submit}><div className="llm-drawer-body"><h2>{editing ? "\u7f16\u8f91\u5de5\u4f5c\u6d41" : "\u6dfb\u52a0\u5de5\u4f5c\u6d41"}</h2><label>{"\u540d\u79f0 *"}<input value={form.name} onChange={(event) => update("name", event.target.value)} /></label><label>{"\u5173\u8054\u8fde\u63a5 *"}<select value={form.connectionId} onChange={(event) => update("connectionId", event.target.value)}>{connections.map((connection) => <option value={connection.id} key={connection.id}>{connection.name}</option>)}</select></label><label>typeConfig JSON<textarea value={form.typeConfigJson} onChange={(event) => update("typeConfigJson", event.target.value)} /></label><label>defaultParameters JSON<textarea value={form.defaultParametersJson} onChange={(event) => update("defaultParametersJson", event.target.value)} /></label><label>Input<input value={form.inputContractVersion} onChange={(event) => update("inputContractVersion", event.target.value)} /></label><label>Output<input value={form.outputContractVersion} onChange={(event) => update("outputContractVersion", event.target.value)} /></label>{error && <p className="llm-form-error">{error}</p>}</div><footer><button type="button" onClick={onClose}>\u53d6\u6d88</button><button className="primary" disabled={saving}>\u4fdd\u5b58</button></footer></form></aside></div>;
}

export function WorkflowSettingsPage() {
  const [workflows, setWorkflows] = useState<ReturnType<typeof mapWorkflow>[] | null>(null); const [connections, setConnections] = useState<WorkflowConnectionDto[] | null>(null); const [drawer, setDrawer] = useState<DrawerState>(null);
  const load = useCallback(async (signal?: AbortSignal) => { const [workflowResult, connectionResult] = await Promise.all([listWorkflows({ signal }), listConnections({ signal })]); setWorkflows(workflowResult.items.map(mapWorkflow)); setConnections(connectionResult.items); }, []);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => void load(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort(); }; }, [load]);
  return <main className="llm-settings"><nav className="llm-tabs"><Link href="/settings?tab=connections">\u5de5\u4f5c\u6d41\u914d\u7f6e</Link><button className="active">\u5de5\u4f5c\u6d41</button></nav><section className="llm-content-card"><header><h2>\u5de5\u4f5c\u6d41\u914d\u7f6e</h2><button className="primary" onClick={() => setDrawer({ mode: "create" })}>\u6dfb\u52a0\u5de5\u4f5c\u6d41</button></header>{!workflows || !connections ? <div className="llm-loading">\u52a0\u8f7d\u4e2d\u2026</div> : workflows.length ? <div className="llm-table-wrap"><table><tbody>{workflows.map((workflow) => <tr key={workflow.id}><td>{workflow.name}</td><td>{workflow.connectionName}</td><td>{workflow.connectionTypeLabel}</td><td><button onClick={async () => setDrawer({ mode: "edit", workflow: await getWorkflow(workflow.id) })}>\u7f16\u8f91</button></td></tr>)}</tbody></table></div> : <div className="llm-state">\u6682\u65e0\u5de5\u4f5c\u6d41\u914d\u7f6e</div>}</section>{drawer && connections && <WorkflowDrawer state={drawer} connections={connections} onClose={() => setDrawer(null)} onSaved={load} />}</main>;
}
