import { apiRequest, type ApiRequestInit } from "../../lib/api.ts";

export type ApplicableStage = "chapter_planning" | "content_generation" | "review" | "rewrite";
export type WorkflowDto = { id:string; name:string; connectionId:string; connectionName:string; connectionType:string; workflowType:string; applicableStages:ApplicableStage[]; typeConfig:{referenceType:"workflow_id"|"webhook_path";referenceValue:string}; inputContractVersion:string; outputContractVersion:string; defaultParameters:Record<string,unknown>; note:string|null; integrationStatus:"not_connected"; enabled:boolean; lastVerifiedAt:string|null; lastErrorCode:string|null; lastErrorMessage:string|null; version:number; createdAt:string; updatedAt:string };
export type WorkflowVm = { id:string; name:string; connectionName:string; connectionTypeLabel:string; stagesLabel:string; statusLabel:string; version:number };
export type WorkflowForm = { name:string; connectionId:string; applicableStages:ApplicableStage[]; referenceType:"workflow_id"|"webhook_path"; referenceValue:string; inputContractVersion:string; outputContractVersion:string; defaultParametersJson:string; note:string };
export type WorkflowListQuery = { q?:string; connectionType?:string; integrationStatus?:"not_connected"; enabled?:boolean; limit?:number; offset?:number };

const stageLabels:Record<ApplicableStage,string>={chapter_planning:"章节规划",content_generation:"内容生成",review:"审核",rewrite:"重写"};
const object = (value:string) => { const parsed:unknown=JSON.parse(value); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("not_object"); return parsed as Record<string,unknown>; };
export const mapWorkflow=(item:WorkflowDto):WorkflowVm=>({id:item.id,name:item.name,connectionName:item.connectionName,connectionTypeLabel:item.connectionType==="n8n"?"n8n":"未知连接类型",stagesLabel:item.applicableStages.map(stage=>stageLabels[stage] ?? "未知环节").join("、"),statusLabel:"未接入",version:item.version});
export function validateWorkflow(form:WorkflowForm) { if (!form.name.trim() || !form.connectionId || !form.applicableStages.length || !form.referenceValue.trim() || !form.inputContractVersion.trim() || !form.outputContractVersion.trim()) return "请完整填写必填字段。"; try { object(form.defaultParametersJson); } catch { return "默认参数必须是 JSON 对象。"; } return undefined; }
export const createWorkflowPayload=(form:WorkflowForm)=>({name:form.name.trim(),connectionId:form.connectionId,applicableStages:form.applicableStages,typeConfig:{referenceType:form.referenceType,referenceValue:form.referenceValue.trim()},inputContractVersion:form.inputContractVersion.trim(),outputContractVersion:form.outputContractVersion.trim(),defaultParameters:object(form.defaultParametersJson),note:form.note.trim()||null});
export const updateWorkflowPayload=(form:WorkflowForm,version:number)=>({expectedVersion:version,...createWorkflowPayload(form)});
const headers=(key:string)=>({"Content-Type":"application/json","Idempotency-Key":key});
export const listWorkflows=(query:WorkflowListQuery={},init?:ApiRequestInit)=>{const params=new URLSearchParams({limit:String(query.limit??20),offset:String(query.offset??0)}); if(query.q?.trim())params.set("q",query.q.trim()); if(query.connectionType)params.set("connectionType",query.connectionType); if(query.integrationStatus)params.set("integrationStatus",query.integrationStatus); if(query.enabled!==undefined)params.set("enabled",String(query.enabled)); return apiRequest<{items:WorkflowDto[];total:number;limit:number;offset:number}>(`/workflow-configurations?${params}`,init);};
export const getWorkflow=(id:string,init?:ApiRequestInit)=>apiRequest<WorkflowDto>(`/workflow-configurations/${encodeURIComponent(id)}`,init);
export const createWorkflow=(form:WorkflowForm,key:string)=>apiRequest<WorkflowDto>("/workflow-configurations",{method:"POST",headers:headers(key),body:JSON.stringify(createWorkflowPayload(form))});
export const updateWorkflow=(id:string,form:WorkflowForm,version:number,key:string)=>apiRequest<WorkflowDto>(`/workflow-configurations/${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(key),body:JSON.stringify(updateWorkflowPayload(form,version))});
