"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { listConnections, type WorkflowConnectionDto } from "./workflow-connection-api";
import { createWorkflow, getWorkflow, listWorkflows, mapWorkflow, updateWorkflow, validateWorkflow, type WorkflowDto, type WorkflowForm } from "./workflow-api";

type DrawerState = { mode: "create" } | { mode: "edit"; workflow: WorkflowDto } | null;
const emptyForm = (connectionId = ""): WorkflowForm => ({ name: "", connectionId, applicableStages: ["review"], typeConfigJson: '{"referenceType":"workflow_id","referenceValue":""}', inputContractVersion: "v1", outputContractVersion: "v1", defaultParametersJson: "{}", note: "" });

function WorkflowDrawer({ state, connections, onClose, onSaved }: { state: Exclude<DrawerState, null>; connections: WorkflowConnectionDto[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const editing = state.mode === "edit";
  const [form, setForm] = useState<WorkflowForm>(() => editing ? { name: state.workflow.name, connectionId: state.workflow.connectionId, applicableStages: state.workflow.applicableStages, typeConfigJson: JSON.stringify(state.workflow.typeConfig, null, 2), inputContractVersion: state.workflow.inputContractVersion, outputContractVersion: state.workflow.outputContractVersion, defaultParametersJson: JSON.stringify(state.workflow.defaultParameters, null, 2), note: state.workflow.note ?? "" } : emptyForm(connections[0]?.id));
  const [error, setError] = useState<string>(); const [conflict, setConflict] = useState(false); const [saving, setSaving] = useState(false);
  const set = <K extends keyof WorkflowForm>(key: K, value: WorkflowForm[K]) => { setForm(current => ({ ...current, [key]: value })); setError(undefined); };
  const reload = async () => { if (!editing) return; setSaving(true); try { const x = await getWorkflow(state.workflow.id); setForm({ name: x.name, connectionId: x.connectionId, applicableStages: x.applicableStages, typeConfigJson: JSON.stringify(x.typeConfig, null, 2), inputContractVersion: x.inputContractVersion, outputContractVersion: x.outputContractVersion, defaultParametersJson: JSON.stringify(x.defaultParameters, null, 2), note: x.note ?? "" }); setConflict(false); setError("已重新加载服务端最新数据，请确认后重新保存。"); } catch { setError("暂时无法加载最新工作流。"); } finally { setSaving(false); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const invalid = validateWorkflow(form); if (invalid) { setError(invalid); return; } setSaving(true); setError(undefined); try { if (editing) await updateWorkflow(state.workflow.id, form, state.workflow.version, crypto.randomUUID()); else await createWorkflow(form, crypto.randomUUID()); await onSaved(); onClose(); } catch (cause) { const api = cause instanceof ApiError ? cause : undefined; if (api?.status === 409 || api?.code === "version_conflict") { setConflict(true); setError("该工作流已被其他操作更新，请重新加载后再保存。"); } else setError("保存失败，请检查输入后重试。"); } finally { setSaving(false); } };
  return <div className="llm-drawer-backdrop"><aside className="llm-drawer" role="dialog" aria-modal="true"><header><div><h2>{editing ? "编辑工作流" : "添加工作流"}</h2><p>工作流类型由关联连接自动推导。</p></div><button type="button" aria-label="关闭" onClick={onClose} disabled={saving}>×</button></header><form onSubmit={submit}><div className="llm-drawer-body"><label>名称 *<input value={form.name} maxLength={160} onChange={event => set("name", event.target.value)} disabled={saving} /></label><label>关联连接 *<select value={form.connectionId} onChange={event => set("connectionId", event.target.value)} disabled={saving}>{connections.map(connection => <option value={connection.id} key={connection.id}>{connection.name}</option>)}</select></label><label>类型配置 (JSON) *<textarea value={form.typeConfigJson} onChange={event => set("typeConfigJson", event.target.value)} disabled={saving} /></label><label>默认参数 (JSON) *<textarea value={form.defaultParametersJson} onChange={event => set("defaultParametersJson", event.target.value)} disabled={saving} /></label><label>输入契约版本 *<input value={form.inputContractVersion} onChange={event => set("inputContractVersion", event.target.value)} disabled={saving} /></label><label>输出契约版本 *<input value={form.outputContractVersion} onChange={event => set("outputContractVersion", event.target.value)} disabled={saving} /></label>{error && <div className="llm-form-error" role="alert">{error}{conflict && <button type="button" onClick={() => void reload()} disabled={saving}>重新加载</button>}</div>}</div><footer><button type="button" onClick={onClose} disabled={saving}>取消</button><button className="primary" disabled={saving}>{saving ? "保存中…" : "保存"}</button></footer></form></aside></div>;
}

export function WorkflowSettingsPage() {
  const [workflows, setWorkflows] = useState<ReturnType<typeof mapWorkflow>[] | null>(null); const [connections, setConnections] = useState<WorkflowConnectionDto[] | null>(null); const [drawer, setDrawer] = useState<DrawerState>(null); const [error, setError] = useState<string>();
  const load = useCallback(async (signal?: AbortSignal) => { setError(undefined); try { const [workflowResult, connectionResult] = await Promise.all([listWorkflows({ signal }), listConnections({ signal })]); setWorkflows(workflowResult.items.map(mapWorkflow)); setConnections(connectionResult.items); } catch (cause) { if (!(cause instanceof ApiError && cause.code === "cancelled")) setError("暂时无法加载工作流配置，请稍后重试。"); } }, []);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  const openEdit = async (workflow: ReturnType<typeof mapWorkflow>) => { try { setDrawer({ mode: "edit", workflow: await getWorkflow(workflow.id) }); } catch { setError("暂时无法读取工作流详情，请重试。"); } };
  return <main className="llm-settings"><header className="llm-page-heading"><p>设置</p><h1>全局设置</h1></header><nav className="llm-tabs"><Link href="/settings?tab=connections">工作流配置</Link><button className="active">工作流</button><Link href="/settings?tab=distribution">分发平台配置</Link></nav><section className="llm-content-card"><header><div><h2>工作流配置</h2><p>管理关联执行连接的可复用工作流。</p></div><button className="primary" onClick={() => setDrawer({ mode: "create" })} disabled={!connections?.length}>添加工作流</button></header>{error ? <div className="llm-state" role="alert"><h3>暂时无法加载</h3><p>{error}</p><button onClick={() => void load()}>重试</button></div> : !workflows || !connections ? <div className="llm-loading" role="status">正在加载工作流配置…</div> : !connections.length ? <div className="llm-state"><h3>请先添加连接</h3><p>工作流必须关联一个已保存的执行连接。</p><Link href="/settings?tab=connections">前往连接配置</Link></div> : workflows.length ? <div className="llm-table-wrap"><table><thead><tr><th>工作流名称</th><th>关联连接</th><th>连接类型</th><th>适用环节</th><th>集成状态</th><th>操作</th></tr></thead><tbody>{workflows.map(workflow => <tr key={workflow.id}><td><strong>{workflow.name}</strong></td><td>{workflow.connectionName}</td><td>{workflow.connectionTypeLabel}</td><td>{workflow.stagesLabel}</td><td><span className="llm-status">{workflow.statusLabel}</span></td><td><button onClick={() => void openEdit(workflow)}>编辑</button></td></tr>)}</tbody></table></div> : <div className="llm-state"><h3>暂无工作流配置</h3><p>添加工作流后，可供后续项目绑定使用。</p></div>}</section>{drawer && connections && <WorkflowDrawer state={drawer} connections={connections} onClose={() => setDrawer(null)} onSaved={load} />}</main>;
}
