import { apiRequest, type ApiRequestInit } from "../../lib/api.ts";

export type ConnectionType = string;
export type N8nTypeConfig = { referenceType: "workflow_id" | "webhook_path"; referenceValue: string };
export type WorkflowConnectionDto = { id:string; name:string; connectionType:ConnectionType; baseUrl:string; authType:"api_key"; timeoutSeconds:number; typeConfig:N8nTypeConfig; hasCredential:boolean; credentialFingerprint:string|null; integrationStatus:"not_connected"; enabled:boolean; lastVerifiedAt:string|null; lastErrorCode:string|null; lastErrorMessage:string|null; version:number; createdAt:string; updatedAt:string };
export type ConnectionTypeDto = { connectionType:ConnectionType; displayName:string; authTypes:"api_key"[]; fieldSchemas:unknown[] };
export type ConnectionVm = { id:string; name:string; typeLabel:string; baseUrl:string; timeoutSeconds:number; referenceLabel:string; hasCredential:boolean; credentialFingerprint:string|null; statusLabel:string; version:number };
export type ConnectionFormInput = { name:string; connectionType:ConnectionType; baseUrl:string; timeoutSeconds:number; typeConfigJson:string; credential:string };
export type ConnectionListQuery = { q?:string; connectionType?:ConnectionType; integrationStatus?:"not_connected"; enabled?:boolean; limit?:number; offset?:number };
const typeLabel = (item:ConnectionTypeDto[], type:ConnectionType) => item.find(x=>x.connectionType===type)?.displayName ?? "\u672a\u77e5\u8fde\u63a5\u7c7b\u578b";
export const mapConnection = (item:WorkflowConnectionDto, types:ConnectionTypeDto[]):ConnectionVm => ({ id:item.id,name:item.name,typeLabel:typeLabel(types,item.connectionType),baseUrl:item.baseUrl,timeoutSeconds:item.timeoutSeconds,referenceLabel:item.typeConfig.referenceType==="workflow_id"?"\u5de5\u4f5c\u6d41 ID":"Webhook \u8def\u5f84",hasCredential:item.hasCredential,credentialFingerprint:item.credentialFingerprint,statusLabel:"\u672a\u63a5\u5165",version:item.version });
const parseConfig=(json:string):N8nTypeConfig=>JSON.parse(json) as N8nTypeConfig;
export function validateConnectionForm(input:ConnectionFormInput, editing:boolean){if(!input.name.trim())return "\u8bf7\u8f93\u5165\u8fde\u63a5\u540d\u79f0\u3002";try{new URL(input.baseUrl.trim());}catch{return "\u8bf7\u8f93\u5165\u6709\u6548\u7684 Base URL\u3002";}if(!Number.isInteger(input.timeoutSeconds)||input.timeoutSeconds<5||input.timeoutSeconds>300)return "\u8bf7\u6c42\u8d85\u65f6\u9700\u4e3a 5 \u81f3 300 \u79d2\u4e4b\u95f4\u7684\u6574\u6570\u3002";let config:N8nTypeConfig;try{config=parseConfig(input.typeConfigJson);}catch{return "\u914d\u7f6e\u4fe1\u606f\u5fc5\u987b\u662f\u6709\u6548 JSON\u3002";}if(!config||!(config.referenceType==="workflow_id"||config.referenceType==="webhook_path")||typeof config.referenceValue!=="string"||!config.referenceValue.trim())return "\u914d\u7f6e\u4fe1\u606f\u9700\u5305\u542b referenceType \u548c referenceValue\u3002";if(!editing&&!input.credential.trim())return "\u8bf7\u8f93\u5165 API Key\u3002";return undefined;}
export const createConnectionPayload=(input:ConnectionFormInput)=>({name:input.name.trim(),connectionType:input.connectionType,baseUrl:input.baseUrl.trim(),authType:"api_key" as const,timeoutSeconds:input.timeoutSeconds,typeConfig:parseConfig(input.typeConfigJson),...(input.credential.trim()?{credential:input.credential}:{})});
export const updateConnectionPayload=(input:Omit<ConnectionFormInput,"connectionType">&{expectedVersion:number})=>({expectedVersion:input.expectedVersion,name:input.name.trim(),baseUrl:input.baseUrl.trim(),authType:"api_key" as const,timeoutSeconds:input.timeoutSeconds,typeConfig:parseConfig(input.typeConfigJson),...(input.credential.trim()?{credential:input.credential}:{})});
const writeHeaders=(key:string)=>({"Content-Type":"application/json","Idempotency-Key":key});
export const listConnectionTypes=(init?:ApiRequestInit)=>apiRequest<{items:ConnectionTypeDto[]}>("/workflow-connection-types",init);
export const listConnections=(query:ConnectionListQuery={},init?:ApiRequestInit)=>{const params=new URLSearchParams({limit:String(query.limit??20),offset:String(query.offset??0)});if(query.q?.trim())params.set("q",query.q.trim());if(query.connectionType)params.set("connectionType",query.connectionType);if(query.integrationStatus)params.set("integrationStatus",query.integrationStatus);if(query.enabled!==undefined)params.set("enabled",String(query.enabled));return apiRequest<{items:WorkflowConnectionDto[];total:number;limit:number;offset:number}>(`/workflow-connections?${params}`,init);};
export const getConnection=(id:string,init?:ApiRequestInit)=>apiRequest<WorkflowConnectionDto>(`/workflow-connections/${encodeURIComponent(id)}`,init);
export const createConnection=(input:ConnectionFormInput,key:string,init?:ApiRequestInit)=>apiRequest<WorkflowConnectionDto>("/workflow-connections",{...init,method:"POST",headers:writeHeaders(key),body:JSON.stringify(createConnectionPayload(input))});
export const updateConnection=(id:string,input:Omit<ConnectionFormInput,"connectionType">&{expectedVersion:number},key:string,init?:ApiRequestInit)=>apiRequest<WorkflowConnectionDto>(`/workflow-connections/${encodeURIComponent(id)}`,{...init,method:"PATCH",headers:writeHeaders(key),body:JSON.stringify(updateConnectionPayload(input))});
