package httpserver

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/google/uuid"
	"github.com/local/ai-content-factory/apps/api/internal/contentitem"
	"github.com/local/ai-content-factory/apps/api/internal/workflowrun"
)

type generationCommandSpy struct { retryCalls,currentCalls int; retry contentitem.RetryConsumptionRequest; current contentitem.SetCurrentRequest; result contentitem.ContentGenerationResult; detail contentitem.Detail }
func (s *generationCommandSpy) RetryConsumption(_ context.Context,_ uuid.UUID,r contentitem.RetryConsumptionRequest)(contentitem.ContentGenerationResult,error){s.retryCalls++;s.retry=r;return s.result,nil}
func (s *generationCommandSpy) SetCurrent(_ context.Context,_ uuid.UUID,r contentitem.SetCurrentRequest)(contentitem.Detail,error){s.currentCalls++;s.current=r;return s.detail,nil}
func generationSpy() *generationCommandSpy { item:=contentitem.ContentItem{ID:uuid.New(),ChapterPlanID:uuid.New(),CurrentVersionID:uuid.New(),Title:"chapter",Status:"draft"}; candidate:=contentitem.ContentVersion{ID:uuid.New(),ContentItemID:item.ID,Title:"candidate",Content:"text",Source:"workflow_generated",Status:"editable_draft",Version:1,VersionNo:2}; item.CurrentVersionID=candidate.ID; return &generationCommandSpy{result:contentitem.ContentGenerationResult{ContentItem:item,CandidateVersion:candidate,WorkflowRun:workflowrun.WorkflowRun{ID:uuid.New(),ProjectID:uuid.New(),RunNumber:"WR-TEST",Stage:"content_generation",Status:workflowrun.StatusSucceeded,Version:1}},detail:contentitem.Detail{Item:item,CurrentVersion:candidate}} }

func generationContractCall(t *testing.T, h http.Handler, method, path, body, key string) *httptest.ResponseRecorder { t.Helper(); r:=httptest.NewRequest(method,path,bytes.NewBufferString(body)); r.SetPathValue("contentItemId",uuid.NewString()); r.SetPathValue("runId",uuid.NewString()); r.Header.Set("Content-Type","application/json"); if key!=""{r.Header.Set("Idempotency-Key",key)}; w:=httptest.NewRecorder(); withRequestID(h).ServeHTTP(w,r); return w }
func generationContractError(t *testing.T,w *httptest.ResponseRecorder){t.Helper();var e struct{Error struct{Code string `json:"code"`} `json:"error"`;RequestID string `json:"request_id"`};if json.Unmarshal(w.Body.Bytes(),&e)!=nil||e.Error.Code!="validation_error"||e.RequestID==""{t.Fatalf("invalid ErrorEnvelope: %s",w.Body.Bytes())}}
func TestContentGenerationResultConsumptionRetryHandlerContractValidation(t *testing.T){h:=contentGenerationRetryHandler(nil);for _,x:=range []struct{body,key string}{{`{"expectedRunVersion":1}`,""},{`{}`,"key"},{`{`,"key"}}{w:=generationContractCall(t,h,http.MethodPost,"/api/v1/content-generation-runs/x/result-consumption-retries",x.body,x.key);if w.Code!=http.StatusBadRequest{t.Fatalf("status=%d body=%s",w.Code,w.Body.Bytes())};generationContractError(t,w)}}
func TestContentGenerationSetCurrentHandlerContractValidation(t *testing.T){h:=contentGenerationCurrentHandler(nil);candidate,current:=uuid.NewString(),uuid.NewString();for _,x:=range []struct{body,key string}{{`{"candidateVersionId":"`+candidate+`","expectedCurrentVersionId":"`+current+`","expectedCurrentVersion":1}`,""},{`{"candidateVersionId":"`+candidate+`","expectedCurrentVersion":1}`,"key"},{`{"candidateVersionId":"`+candidate+`","expectedCurrentVersionId":"`+current+`"}`,"key"},{`{`,"key"}}{w:=generationContractCall(t,h,http.MethodPost,"/api/v1/content-items/x/current-version",x.body,x.key);if w.Code!=http.StatusBadRequest{t.Fatalf("status=%d body=%s",w.Code,w.Body.Bytes())};generationContractError(t,w)}}
func TestContentGenerationCommandHandlerSuccessEnvelopesAndIsolation(t *testing.T){spy:=generationSpy();retry:=generationContractCall(t,contentGenerationRetryHandler(spy),http.MethodPost,"/api/v1/content-generation-runs/x/result-consumption-retries",`{"expectedRunVersion":1}`,"retry-key");if retry.Code!=200||spy.retryCalls!=1||spy.currentCalls!=0||spy.retry.ExpectedRunVersion!=1||spy.retry.IdempotencyKey!="retry-key"{t.Fatalf("retry mapping: %d %s",retry.Code,retry.Body.Bytes())};var re struct{Data struct{ContentItem json.RawMessage `json:"contentItem"`;Candidate json.RawMessage `json:"candidateVersion"`;Run json.RawMessage `json:"workflowRun"`} `json:"data"`;RequestID string `json:"request_id"`};if json.Unmarshal(retry.Body.Bytes(),&re)!=nil||len(re.Data.ContentItem)==0||len(re.Data.Candidate)==0||len(re.Data.Run)==0||re.RequestID==""{t.Fatalf("retry envelope: %s",retry.Body.Bytes())};candidate,current:=spy.detail.CurrentVersion.ID,spy.detail.CurrentVersion.ID;body:=`{"candidateVersionId":"`+candidate.String()+`","expectedCurrentVersionId":"`+current.String()+`","expectedCurrentVersion":1}`;set:=generationContractCall(t,contentGenerationCurrentHandler(spy),http.MethodPost,"/api/v1/content-items/x/current-version",body,"set-key");if set.Code!=200||spy.currentCalls!=1||spy.current.ExpectedCurrentVersion!=1||spy.current.IdempotencyKey!="set-key"{t.Fatalf("set mapping: %d %s",set.Code,set.Body.Bytes())};var se struct{Data struct{Item json.RawMessage `json:"content_item"`;Current json.RawMessage `json:"current_version"`} `json:"data"`;RequestID string `json:"request_id"`};if json.Unmarshal(set.Body.Bytes(),&se)!=nil||len(se.Data.Item)==0||len(se.Data.Current)==0||se.RequestID==""{t.Fatalf("set envelope: %s",set.Body.Bytes())}}

func TestContentGenerationSummaryLatestErrorPresenter(t *testing.T){spy:=generationSpy();summary:=contentitem.GenerationSummary{Detail:spy.detail,State:"runtime_failed",LatestError:&contentitem.GenerationSafeError{Code:"runtime_failed",Message:"workflow execution failed",Details:map[string]any{}}};response:=contentGenerationSummaryResponse(summary);latest,ok:=response["latestError"].(map[string]any);if !ok||latest["message"]!="workflow execution failed"||latest["code"]!="runtime_failed"{t.Fatalf("latestError=%#v",response["latestError"])};summary.LatestError=nil;response=contentGenerationSummaryResponse(summary);if response["latestError"]!=nil{t.Fatalf("non-failure latestError=%#v",response["latestError"])} }
