package httpserver

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/local/ai-content-factory/apps/api/internal/contentitem"
	"github.com/local/ai-content-factory/apps/api/internal/workflowrun"
)

func registerContentGenerationRoutes(mux *http.ServeMux, app *contentitem.GenerationService) { mux.HandleFunc("POST /api/v1/content-items/{contentItemId}/content-generation-runs/preflight", contentGenerationPreflightHandler(app)); mux.HandleFunc("POST /api/v1/content-items/{contentItemId}/content-generation-runs", contentGenerationCreateHandler(app)); mux.HandleFunc("GET /api/v1/content-items/{contentItemId}/content-generation-summary", contentGenerationSummaryHandler(app)); mux.HandleFunc("POST /api/v1/content-generation-runs/{runId}/result-consumption-retries", contentGenerationRetryHandler(app)); mux.HandleFunc("POST /api/v1/content-items/{contentItemId}/current-version", contentGenerationCurrentHandler(app)) }
type contentGenerationPreflightRequest struct { ExpectedCurrentVersionID string `json:"expectedCurrentVersionId"`; ExpectedCurrentVersion int `json:"expectedCurrentVersion"`; ContextOptions contentitem.GenerationContextOptions `json:"contextOptions"`; AdditionalInstructions *string `json:"additionalInstructions"` }
type contentGenerationCreateRequest struct { PreflightToken string `json:"preflightToken"` }
type contentGenerationRetryRequest struct { ExpectedRunVersion int `json:"expectedRunVersion"` }
type contentGenerationCurrentRequest struct { CandidateVersionID string `json:"candidateVersionId"`; ExpectedCurrentVersionID string `json:"expectedCurrentVersionId"`; ExpectedCurrentVersion int `json:"expectedCurrentVersion"` }
type contentGenerationCommandService interface { RetryConsumption(context.Context, uuid.UUID, contentitem.RetryConsumptionRequest) (contentitem.ContentGenerationResult,error); SetCurrent(context.Context,uuid.UUID,contentitem.SetCurrentRequest)(contentitem.Detail,error) }
func contentGenerationItemID(w http.ResponseWriter,r *http.Request)(uuid.UUID,bool){ id,e:=uuid.Parse(r.PathValue("contentItemId")); if e!=nil { writeError(w,r,400,"invalid_uuid","contentItemId must be a UUID",map[string]any{}); return uuid.Nil,false }; return id,true }
func contentGenerationPreflightHandler(app *contentitem.GenerationService) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request){ id,ok:=contentGenerationItemID(w,r); if !ok{return}; var body contentGenerationPreflightRequest; if decodeBody(r,&body)!=nil { writeError(w,r,400,"validation_error","invalid request body",map[string]any{}); return }; version,e:=uuid.Parse(body.ExpectedCurrentVersionID); if e!=nil { writeError(w,r,400,"validation_error","expectedCurrentVersionId must be a UUID",map[string]any{});return }; result,e:=app.Preflight(r.Context(),id,contentitem.GenerationPreflightRequest{ExpectedCurrentVersionID:version,ExpectedCurrentVersion:body.ExpectedCurrentVersion,ContextOptions:body.ContextOptions,AdditionalInstructions:normalizedInstructions(body.AdditionalInstructions),ActorID:requestActorID(r)}); if e!=nil { contentGenerationError(w,r,e);return }; writeJSON(w,r,200,contentGenerationPreflightResponse(result)) } }
func contentGenerationCreateHandler(app *contentitem.GenerationService) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request){ id,ok:=contentGenerationItemID(w,r);if !ok{return}; key:=strings.TrimSpace(r.Header.Get("Idempotency-Key"));if key=="" { writeError(w,r,400,"validation_error","Idempotency-Key is required",map[string]any{});return };var body contentGenerationCreateRequest;if decodeBody(r,&body)!=nil||strings.TrimSpace(body.PreflightToken)=="" {writeError(w,r,400,"validation_error","invalid request body",map[string]any{});return};run,e:=app.CreateRun(r.Context(),id,requestActorID(r),body.PreflightToken,key);if e!=nil {contentGenerationError(w,r,e);return};writeJSON(w,r,201,iteration14WorkflowRunResponse(run)) } }
func contentGenerationSummaryHandler(app *contentitem.GenerationService) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request){id,ok:=contentGenerationItemID(w,r);if !ok{return};summary,e:=app.Summary(r.Context(),id);if e!=nil {contentGenerationError(w,r,e);return};writeJSON(w,r,200,contentGenerationSummaryResponse(summary))} }
func contentGenerationRetryHandler(app contentGenerationCommandService) http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){id,e:=uuid.Parse(r.PathValue("runId"));if e!=nil{writeError(w,r,400,"invalid_uuid","runId must be a UUID",map[string]any{});return};key:=strings.TrimSpace(r.Header.Get("Idempotency-Key"));var body contentGenerationRetryRequest;if key==""||len(key)>128||decodeBody(r,&body)!=nil||body.ExpectedRunVersion<1{writeError(w,r,400,"validation_error","invalid request body or Idempotency-Key",map[string]any{});return};v,e:=app.RetryConsumption(r.Context(),id,contentitem.RetryConsumptionRequest{ExpectedRunVersion:body.ExpectedRunVersion,IdempotencyKey:key});if e!=nil{contentGenerationError(w,r,e);return};writeJSON(w,r,200,contentGenerationResultResponse(v))}}
func contentGenerationCurrentHandler(app contentGenerationCommandService) http.HandlerFunc{return func(w http.ResponseWriter,r *http.Request){id,ok:=contentGenerationItemID(w,r);if !ok{return};key:=strings.TrimSpace(r.Header.Get("Idempotency-Key"));var body contentGenerationCurrentRequest;if key==""||len(key)>128||decodeBody(r,&body)!=nil||body.ExpectedCurrentVersion<1{writeError(w,r,400,"validation_error","invalid request body or Idempotency-Key",map[string]any{});return};candidate,e:=uuid.Parse(body.CandidateVersionID);if e!=nil{writeError(w,r,400,"validation_error","candidateVersionId must be a UUID",map[string]any{});return};current,e:=uuid.Parse(body.ExpectedCurrentVersionID);if e!=nil{writeError(w,r,400,"validation_error","expectedCurrentVersionId must be a UUID",map[string]any{});return};v,e:=app.SetCurrent(r.Context(),id,contentitem.SetCurrentRequest{CandidateVersionID:candidate,ExpectedCurrentVersionID:current,ExpectedCurrentVersion:body.ExpectedCurrentVersion,IdempotencyKey:key});if e!=nil{contentGenerationError(w,r,e);return};writeJSON(w,r,200,contentDetailResponse(v))}}
func normalizedInstructions(v *string)*string { if v==nil{return nil}; x:=strings.TrimSpace(*v);if x==""{return nil};return &x }
func contentGenerationPreflightResponse(v contentitem.GenerationPreflightResult) map[string]any { var token any;var expires any;if v.Passed { token=v.Token;expires=v.ExpiresAt.UTC().Format(time.RFC3339Nano) }; checks:=make([]map[string]any,0,len(v.Checks));for _,x:=range v.Checks{checks=append(checks,map[string]any{"code":x.Code,"status":x.Status,"message":x.Message})}; var workflow any;if v.Workflow!=nil{workflow=map[string]any{"workflowConfigurationId":v.Workflow.ID,"name":v.Workflow.Name,"inputContractVersion":v.Workflow.InputContractVersion,"outputContractVersion":v.Workflow.OutputContractVersion,"configurationVersion":v.Workflow.Version}};return map[string]any{"status":map[bool]string{true:"passed",false:"blocked"}[v.Passed],"preflightToken":token,"expiresAt":expires,"sourceVersion":contentGenerationVersion(v.SourceVersion),"targetVersionNo":v.TargetVersionNo,"workflow":workflow,"contextSummary":map[string]any{"chapterGoalCount":v.ContextSummary.ChapterGoalCount,"keyPlotCount":v.ContextSummary.KeyPlotCount,"priorChapterCount":v.ContextSummary.PriorChapterCount,"materialCount":v.ContextSummary.MaterialCount,"storylineCount":v.ContextSummary.StorylineCount,"foreshadowingCount":v.ContextSummary.ForeshadowingCount},"checks":checks} }
func contentGenerationSummaryResponse(v contentitem.GenerationSummary) map[string]any { var active,latest,candidate any;if v.ActiveRun!=nil{active=iteration14WorkflowRunResponse(*v.ActiveRun)};if v.LatestRun!=nil{latest=iteration14WorkflowRunResponse(*v.LatestRun)};if v.LatestCandidate!=nil{candidate=contentGenerationVersion(*v.LatestCandidate)};events:=make([]any,0,len(v.LatestEvents));for _,e:=range v.LatestEvents {events=append(events,map[string]any{"id":e.ID,"runId":e.RunID,"eventType":e.EventType,"status":e.Status,"payload":e.Payload,"createdAt":e.CreatedAt.UTC().Format(time.RFC3339Nano)})}; var reviewed any;if v.Detail.Item.ReviewedAt!=nil{reviewed=v.Detail.Item.ReviewedAt.UTC().Format(time.RFC3339Nano)};return map[string]any{"contentItemId":v.Detail.Item.ID,"contentItem":map[string]any{"id":v.Detail.Item.ID,"chapter_plan_id":v.Detail.Item.ChapterPlanID,"title":v.Detail.Item.Title,"status":v.Detail.Item.Status,"current_version_id":v.Detail.Item.CurrentVersionID,"reviewed_at":reviewed,"created_at":v.Detail.Item.CreatedAt.UTC().Format(time.RFC3339Nano),"updated_at":v.Detail.Item.UpdatedAt.UTC().Format(time.RFC3339Nano)},"currentVersionId":v.Detail.CurrentVersion.ID,"currentVersion":contentGenerationVersion(v.Detail.CurrentVersion),"workflowConfigured":v.WorkflowConfigured,"state":v.State,"activeRun":active,"latestRun":latest,"latestEvents":events,"latestCandidateVersion":candidate,"latestError":nil,"canGenerate":v.CanGenerate,"candidateCanBecomeCurrent":v.CandidateCanBecomeCurrent} }
func contentGenerationVersion(v contentitem.ContentVersion) map[string]any{return map[string]any{"id":v.ID,"content_item_id":v.ContentItemID,"version_no":v.VersionNo,"title":v.Title,"content":v.Content,"summary":v.Summary,"word_count":v.WordCount,"source":v.Source,"status":v.Status,"generation_parameters":json.RawMessage(v.GenerationParameters),"version":v.Version,"frozen_at":v.FrozenAt,"created_at":v.CreatedAt.UTC().Format(time.RFC3339Nano),"updated_at":v.UpdatedAt.UTC().Format(time.RFC3339Nano),"source_content_version_id":v.SourceContentVersionID,"source_content_version_version":v.SourceContentVersionVersion,"source_workflow_run_id":v.SourceWorkflowRunID}}
func contentGenerationResultResponse(v contentitem.ContentGenerationResult) map[string]any{return map[string]any{"contentItem":contentItemGenerationResponse(v.ContentItem),"candidateVersion":contentGenerationVersion(v.CandidateVersion),"workflowRun":iteration14WorkflowRunResponse(v.WorkflowRun)}}
func contentItemGenerationResponse(v contentitem.ContentItem) map[string]any{var reviewed any;if v.ReviewedAt!=nil{reviewed=v.ReviewedAt.UTC().Format(time.RFC3339Nano)};return map[string]any{"id":v.ID,"chapter_plan_id":v.ChapterPlanID,"title":v.Title,"status":v.Status,"current_version_id":v.CurrentVersionID,"reviewed_at":reviewed,"created_at":v.CreatedAt.UTC().Format(time.RFC3339Nano),"updated_at":v.UpdatedAt.UTC().Format(time.RFC3339Nano)}}
func contentGenerationError(w http.ResponseWriter,r *http.Request,e error){switch{case errors.Is(e,contentitem.ErrContentItemNotFound):writeError(w,r,404,"content_item_not_found","content item not found",map[string]any{});case errors.Is(e,workflowrun.ErrNotFound):writeError(w,r,404,"validation_error","workflow run not found",map[string]any{});case errors.Is(e,contentitem.ErrGenerationNotConfigured):writeError(w,r,422,"workflow_not_configured","正文生成工作流尚未配置",map[string]any{});case errors.Is(e,contentitem.ErrGenerationActiveRun):writeError(w,r,409,"active_run_conflict","当前正文已有生成任务",map[string]any{});case errors.Is(e,contentitem.ErrGenerationInputChanged):writeError(w,r,409,"current_version_changed","当前正文版本已变化",map[string]any{});case errors.Is(e,contentitem.ErrGenerationTokenExpired):writeError(w,r,422,"preflight_token_expired","预检令牌已过期",map[string]any{});case errors.Is(e,contentitem.ErrGenerationTokenConsumed):writeError(w,r,422,"preflight_token_consumed","预检令牌已使用",map[string]any{});case errors.Is(e,contentitem.ErrGenerationTokenInvalid):writeError(w,r,422,"preflight_token_invalid","预检令牌无效",map[string]any{});case errors.Is(e,contentitem.ErrCandidateStale):writeError(w,r,409,"candidate_source_stale","候选版本基线已过期",map[string]any{});case errors.Is(e,contentitem.ErrCandidateNotEligible):writeError(w,r,409,"content_version_not_candidate","content version is not an eligible candidate",map[string]any{});case errors.Is(e,contentitem.ErrCandidateItemMismatch):writeError(w,r,409,"content_version_item_mismatch","candidate belongs to another content item",map[string]any{});case errors.Is(e,contentitem.ErrRunNotConsumable):writeError(w,r,409,"result_consumption_failed","workflow run cannot be consumed",map[string]any{});case errors.Is(e,contentitem.ErrGenerationSourceInvalid):writeError(w,r,500,"result_consumption_failed","source content version is no longer valid",map[string]any{});case errors.Is(e,workflowrun.ErrVersionConflict):writeError(w,r,409,"current_version_changed","version conflict",map[string]any{});case errors.Is(e,workflowrun.ErrIdempotencyConflict):writeError(w,r,409,"idempotency_key_reused_with_different_payload","幂等键与请求不匹配",map[string]any{});case errors.Is(e,contentitem.ErrValidation):writeError(w,r,400,"validation_error","请求无效",map[string]any{});default:writeError(w,r,500,"internal_error","internal server error",map[string]any{})}}
