"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useRef, useState } from "react";
import { ApiError } from "@/lib/api";
import { getOrCreateOperation, clearOperation } from "@/features/chapter-plans/use-idempotency";
import { createContentGenerationRun, preflightContentGenerationRun, type ContentGenerationContextOptions, type ContentGenerationPreflightReport, type ContentVersion } from "./content-item-http-api";

const initialOptions: ContentGenerationContextOptions = { includePriorChapterSummaries: true, includeProjectMaterials: true, includeStoryContext: true, includeForeshadowings: true };
const errorText = (error: unknown) => { const api = error as ApiError; return api?.code === "preflight_token_expired" || api?.code === "preflight_input_changed" || api?.code === "current_version_changed" || api?.code === "active_run_conflict" ? "当前条件已变化，请重新预检后再创建任务。" : "创建生成任务失败，已保留填写内容，请稍后重试。"; };
export function ContentGenerationDrawer({ contentItemId, version, onClose, onCreated }: { contentItemId: string; version: ContentVersion; onClose: () => void; onCreated: () => Promise<void> }) {
  const [instructions, setInstructions] = useState(""); const [options, setOptions] = useState(initialOptions); const [report, setReport] = useState<ContentGenerationPreflightReport | null>(null); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const submitted = useRef(false);
  const request = () => ({ expectedCurrentVersionId: version.id, expectedCurrentVersion: version.version, contextOptions: options, additionalInstructions: instructions.trim() || null });
  const preflight = async () => { setLoading(true); setError(null); setReport(null); clearOperation(`content-generation:${contentItemId}`); try { setReport(await preflightContentGenerationRun(contentItemId, request())); } catch { setError("预检失败，请检查网络后重试。"); } finally { setLoading(false); } };
  useEffect(() => { void preflight(); }, []); // opening the drawer always starts a fresh, read-only preflight
  const submit = async () => { if (!report || report.status !== "passed" || !report.preflightToken || submitting || submitted.current) return; submitted.current = true; setSubmitting(true); setError(null); const payload = { preflightToken: report.preflightToken }; const scope = `content-generation:${contentItemId}`; try { const key = await getOrCreateOperation(scope, payload); await createContentGenerationRun(contentItemId, payload, key); clearOperation(scope); await onCreated(); onClose(); } catch (cause) { submitted.current = false; setError(errorText(cause)); } finally { setSubmitting(false); } };
  return <div className="content-generate-backdrop"><section className="content-generate-dialog content-generation-drawer" role="dialog" aria-modal="true" aria-labelledby="content-generation-title"><header><div><h2 id="content-generation-title">生成正文</h2><p>以当前 v{version.version_no} 为基线；预检不会修改正文或创建任务。</p></div><button aria-label="关闭生成正文抽屉" onClick={onClose} disabled={submitting}>×</button></header><div>{loading && <p>正在预检生成条件…</p>}{!loading && <><label>本次补充要求<textarea value={instructions} maxLength={2000} onChange={(e) => { setInstructions(e.target.value); setReport(null); }} disabled={submitting} placeholder="可选：补充本次创作要求" /></label><fieldset><legend>上下文选项</legend>{Object.entries({ includePriorChapterSummaries: "包含前章摘要", includeProjectMaterials: "包含项目素材", includeStoryContext: "包含故事情报", includeForeshadowings: "包含关联伏笔" }).map(([key, label]) => <label key={key}><input type="checkbox" checked={options[key as keyof ContentGenerationContextOptions]} onChange={(e) => setOptions((v) => ({ ...v, [key]: e.target.checked }))} disabled={submitting} /> {label}</label>)}</fieldset>{report ? <section className={report.status === "passed" ? "content-preflight-passed" : "content-preflight-blocked"}><h3>{report.status === "passed" ? "预检通过" : "预检未通过"}</h3>{report.checks.map((check) => <p key={check.code}>{check.status === "blocked" ? "阻断：" : "通过："}{check.message}</p>)}{report.status === "passed" && <><p>基线版本：v{report.sourceVersion.version_no}；将创建 v{report.targetVersionNo} 候选版本。</p><p>工作流：{report.workflow?.name ?? "已配置"}（配置版本 {report.workflow?.configurationVersion ?? "—"}）</p></>}</section> : <button type="button" onClick={() => void preflight()} disabled={submitting}>重新预检</button>}</>}{error && <p className="content-inline-error" role="alert">{error}</p>}</div><footer><button onClick={onClose} disabled={submitting}>取消</button>{report?.status === "passed" && <button onClick={() => void submit()} disabled={submitting}>{submitting ? "正在创建…" : "确认创建生成任务"}</button>}</footer></section></div>;
}
