"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Icon } from "@/components/ui/icons";
import { ApiError, getProjectWorkspace } from "@/lib/api";
import { listProjectMaterialsFromApi } from "../api/project-material-http-api";
import { ProjectWorkspaceNav } from "../components/project-workspace-nav";
import type { MaterialType, ProjectMaterialList, ProjectMaterialSort } from "../contracts/materials";
const labels: Record<MaterialType,string>={character:"人物",worldview:"世界观",location:"地点",organization:"组织",item:"道具",reference:"参考资料"}; const types=Object.keys(labels) as MaterialType[];
const date=(v:string)=>new Date(v).toLocaleString("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"});
export function MaterialsPage({projectId}:{projectId:string}){const [project,setProject]=useState<{name:string;description:string}|null>(null);const [data,setData]=useState<ProjectMaterialList|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<ApiError|null>(null);const [searchDraft,setSearchDraft]=useState("");const [q,setQ]=useState("");const [type,setType]=useState<MaterialType|undefined>();const [sort,setSort]=useState<ProjectMaterialSort>("updated_at_desc");const [offset,setOffset]=useState(0);const limit=6;
const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError(null);try{const [p,d]=await Promise.all([getProjectWorkspace(projectId).then(({project})=>project),listProjectMaterialsFromApi(projectId,{q,type,sort,limit,offset},{signal})]);if(signal?.aborted)return;setProject(p);setData(d)}catch(e){if(signal?.aborted)return;setError(e instanceof ApiError?e:new ApiError("Unable to load project materials.",500))}finally{if(!signal?.aborted)setLoading(false)}},[projectId,q,type,sort,offset]);useEffect(()=>{const controller=new AbortController();const t=window.setTimeout(()=>void load(controller.signal),0);return()=>{clearTimeout(t);controller.abort()}},[load]);
if(loading)return <MaterialsSkeleton/>; if(error?.code==="PROJECT_NOT_FOUND")return <MaterialsState icon="folder" title="项目不存在" desc="该项目可能已被删除，或项目地址不正确。" projectId={projectId}/>;if(error)return <MaterialsState icon="info" title="暂时无法加载项目素材" desc="请检查网络后重试。" projectId={projectId} retry={()=>void load()}/>;if(!data||!project)return null;const clear=()=>{setSearchDraft("");setQ("");setType(undefined);setOffset(0)};const noResults=data.total===0&&Boolean(q.trim()||type);
return <div className="materials-workspace"><header className="materials-header"><div><p>项目 / {project.name}</p><h1>{project.name}<span>小说</span><b>策划中</b></h1></div></header><ProjectWorkspaceNav projectId={projectId} active="materials"/><main className="materials-main"><section className="materials-heading"><div><h2>素材</h2><p>{project.description||"管理项目创作所需的全部素材。"}</p></div><div><Link href={`/projects/${projectId}/materials/pick`}>选择已有素材</Link><Link className="primary" href={`/projects/${projectId}/materials/new`}><Icon name="plus" size={17}/>新建素材</Link></div></section><nav className="material-counts"><button className={!type?"active":""} onClick={()=>{setType(undefined);setOffset(0)}}>全部 ({Object.values(data.type_counts).reduce((a,b)=>a+b,0)})</button>{types.map(t=><button className={type===t?"active":""} onClick={()=>{setType(t);setOffset(0)}} key={t}>{labels[t]} ({data.type_counts[t]})</button>)}</nav><section className="materials-filters"><label><Icon name="search" size={17}/><input value={searchDraft} onChange={e=>setSearchDraft(e.target.value)} onBlur={()=>{setQ(searchDraft.trim());setOffset(0)}} onKeyDown={e=>{if(e.key==="Enter"){setQ(searchDraft.trim());setOffset(0)}}} placeholder="搜索项目素材"/></label><select value={sort} onChange={e=>{setSort(e.target.value as ProjectMaterialSort);setOffset(0)}}><option value="updated_at_desc">最近更新</option><option value="updated_at_asc">最早更新</option><option value="name_asc">名称 A-Z</option><option value="name_desc">名称 Z-A</option></select></section>{data.total>0?<><section className="materials-grid">{data.items.map(({material,usage,last_updated_at})=><Link className="material-card" href={`/projects/${projectId}/materials/${material.id}`} key={material.id}><header><span className={`material-icon ${material.type}`}><Icon name={material.type==="character"?"home":material.type==="location"?"image":material.type==="item"?"archive":"book"} size={23}/></span><div><h3>{material.name}</h3><p><b>{labels[material.type]}</b>{usage.role_name&&<i>{usage.role_name}</i>}</p></div></header><p className="material-summary">{material.summary}</p><div className="material-tags">{material.tags_json.map(tag=><span key={tag}>{tag}</span>)}</div><dl><div><dt>用途</dt><dd>{usage.usage_type}</dd></div><div><dt>章节范围</dt><dd>{usage.start_chapter?`${usage.start_chapter}–${usage.end_chapter??"后续"}`:"全局"}</dd></div></dl><footer>最近更新：{date(last_updated_at)}</footer></Link>)}</section><Pagination total={data.total} limit={data.limit} offset={data.offset} setOffset={setOffset}/></>:<div className="materials-empty"><Icon name={noResults?"search":"archive"} size={32}/><h3>{noResults?"没有符合条件的素材":"尚未添加项目素材"}</h3><p>{noResults?"试试清除搜索或类型筛选。":"从素材库选择已有内容，或新建一条项目素材。"}</p>{noResults?<button onClick={clear}>清除筛选</button>:<div><Link href={`/projects/${projectId}/materials/pick`}>选择已有素材</Link><Link className="primary" href={`/projects/${projectId}/materials/new`}>新建素材</Link></div>}</div>}</main></div>}
function Pagination({total,limit,offset,setOffset}:{total:number;limit:number;offset:number;setOffset:(n:number)=>void}){const page=Math.floor(offset/limit)+1,pages=Math.ceil(total/limit);return <footer className="materials-pagination"><span>共 {total} 条素材</span><button disabled={page===1} onClick={()=>setOffset(Math.max(0,offset-limit))}>上一页</button><b>{page} / {pages}</b><button disabled={page===pages} onClick={()=>setOffset(offset+limit)}>下一页</button></footer>}
function MaterialsState({icon,title,desc,projectId,retry}:{icon:"folder"|"info";title:string;desc:string;projectId:string;retry?:()=>void}){return <main className="materials-state"><Icon name={icon} size={32}/><h1>{title}</h1><p>{desc}</p><div>{retry&&<button onClick={retry}>重试</button>}<Link href="/projects">返回项目列表</Link><Link href={`/projects/${projectId}`}>项目概览</Link></div></main>}
function MaterialsSkeleton(){return <div className="materials-workspace"><div className="materials-skeleton h"/><div className="materials-skeleton n"/><main className="materials-main"><div className="materials-skeleton title"/><div className="materials-skeleton bar"/><div className="materials-grid">{[1,2,3,4,5,6].map(x=><div className="materials-skeleton card" key={x}/>)}</div></main></div>}
