"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { listGlobalMaterials, listGlobalWorks, type MaterialVm, type WorkVm } from "./global-lite-api";
import type { MaterialType } from "@/features/planning-materials/contracts/materials";
const limit=2;
const typeLabel:Record<MaterialType,string>={character:"人物",worldview:"世界观",location:"地点",organization:"组织",item:"道具",reference:"参考资料"};
function Pager({offset,total,setOffset}:{offset:number;total:number;setOffset:(value:number)=>void}){const page=Math.floor(offset/limit)+1;const pages=Math.max(1,Math.ceil(total/limit));return <footer className="lite-pager"><span>第 {page} / {pages} 页</span><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-limit))}>上一页</button><button disabled={offset+limit>=total} onClick={()=>setOffset(offset+limit)}>下一页</button></footer>}
function State({error,retry,empty}:{error:ApiError|null;retry:()=>void;empty:string}){return <section className="lite-state">{error?<><h2>暂时无法加载</h2><p>{error.message}</p><button onClick={retry}>重试</button></>:<><h2>{empty}</h2><p>当前筛选条件下没有可展示的内容。</p></>}</section>}
export function GlobalMaterialsPage(){const [type,setType]=useState<MaterialType|undefined>();const [offset,setOffset]=useState(0);const [data,setData]=useState<{items:MaterialVm[];total:number}|null>(null);const [error,setError]=useState<ApiError|null>(null);const load=useCallback(()=>{setData(null);setError(null);void listGlobalMaterials({type,limit,offset}).then(setData).catch((cause:ApiError)=>setError(cause));},[offset,type]);useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer)},[load]);return <main className="lite-main"><header><h1>素材</h1><p>查看和管理跨项目复用的人物、世界观、地点、组织、道具与参考资料</p></header><p className="lite-notice">在项目内创建的素材会自动同步到全局素材，并保留各项目中的用途配置。</p><div className="lite-filters"><label>类型 <select value={type??""} onChange={event=>{setType((event.target.value as MaterialType)||undefined);setOffset(0)}}><option value="">全部类型</option>{Object.entries(typeLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>{!data?<>{error?<State error={error} retry={load} empty=""/>:<div className="lite-loading">正在加载全局素材…</div>}</>:data.items.length?<><p className="lite-count">共 {data.total} 个素材</p><section className="lite-grid">{data.items.map(item=><MaterialCard item={item} key={item.id}/>)}</section><Pager offset={offset} total={data.total} setOffset={setOffset}/></>:<State error={null} retry={load} empty="暂无素材"/>}</main>}
function MaterialCard({item}:{item:MaterialVm}){const reference=item.references[0];return <article className="lite-card"><div><span className="lite-kind">{typeLabel[item.type]}</span><h2>{item.name}</h2><p>{item.summary}</p></div><div className="lite-reference">{reference?<><b>{item.references.length>1?`已被 ${item.references.length} 个项目使用`:`引用项目：${reference.project_name}`}</b><span>用途配置：{reference.role_name}</span></>:<span>暂未被项目使用</span>}</div><footer><time>更新：{new Date(item.updated_at).toLocaleDateString("zh-CN")}</time>{reference&&<><Link href={`/projects/${reference.project_id}/materials/${item.id}`}>查看详情</Link><Link href={`/projects/${reference.project_id}`}>打开项目</Link></>}</footer></article>}
export function GlobalWorksPage(){const [offset,setOffset]=useState(0);const [data,setData]=useState<{items:WorkVm[];total:number}|null>(null);const [error,setError]=useState<ApiError|null>(null);const load=useCallback(()=>{setData(null);setError(null);void listGlobalWorks({limit,offset}).then(setData).catch((cause:ApiError)=>setError(cause));},[offset]);useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer)},[load]);return <main className="lite-main"><header><h1>作品</h1><p>查看跨项目的章节正文、当前版本、审核与最近流程结果。</p></header><p className="lite-notice">作品为只读聚合；当前版本与审核、流程摘要直接使用接口返回字段。</p>{!data?<>{error?<State error={error} retry={load} empty=""/>:<div className="lite-loading">正在加载全局作品…</div>}</>:data.items.length?<><section className="lite-grid">{data.items.map(item=><WorkCard item={item} key={item.work.work_id}/>)}</section><Pager offset={offset} total={data.total} setOffset={setOffset}/></>:<State error={null} retry={load} empty="暂无作品"/>}</main>}
function WorkCard({item}:{item:WorkVm}){const {work,project}=item;const run=work.latest_workflow_run;return <article className="lite-card"><div><span className="lite-kind">{project.name}</span><h2>{work.content_item.title}</h2><p>当前版本 v{work.current_version.version_no} · 共 {work.version_count} 个版本 · {work.current_version.word_count.toLocaleString()} 字</p></div><dl className="lite-meta"><div><dt>审核</dt><dd>{work.latest_review?`${work.latest_review.conclusion === "pass"?"通过":"建议修订"} · ${work.latest_review.score}`:"暂无审核"}</dd></div><div><dt>最近流程</dt><dd>{run?run.status==="succeeded"?"已成功":run.status==="failed"?"失败":"运行中":"暂无流程"}</dd></div></dl><footer><Link href={`/projects/${project.id}/works`}>查看项目作品</Link><Link href={`/projects/${project.id}`}>打开项目</Link></footer></article>}
