"use client";

import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import "./llm-settings.css";
import { createLlmProvider, getLlmProvider, listLlmProviderTypes, listLlmProviders, mapLlmProvider, updateLlmProvider, validateProviderForm, type LlmProviderDto, type LlmProviderType, type LlmProviderTypeDto, type LlmProviderVm, type ProviderFormInput } from "@/features/global-config/llm-provider-api";

type Drawer = { mode: "create" } | { mode: "edit"; provider: LlmProviderDto } | null;
const blank = (providerType: LlmProviderType = "openai_compatible"): ProviderFormInput => ({ name: "", providerType, baseUrl: "", defaultModel: "", timeoutSeconds: 60, secret: "" });

function ProviderDrawer({ drawer, types, onClose, onSaved }: { drawer: Exclude<Drawer, null>; types: LlmProviderTypeDto[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const editing = drawer.mode === "edit"; const initial = (): ProviderFormInput => editing ? { name: drawer.provider.name, providerType: drawer.provider.providerType, baseUrl: drawer.provider.baseUrl, defaultModel: drawer.provider.defaultModel, timeoutSeconds: drawer.provider.timeoutSeconds, secret: "" } : blank(types[0]?.providerType);
  const [form, setForm] = useState(initial); const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false); const [conflict, setConflict] = useState(false); const secretSupported = types.find(type => type.providerType === form.providerType)?.supportsSecret ?? true;
  const set = <K extends keyof ProviderFormInput>(key: K, value: ProviderFormInput[K]) => { setForm(current => ({ ...current, [key]: value })); setError(undefined); };
  const reload = async () => { if (!editing) return; setSaving(true); try { const provider = await getLlmProvider(drawer.provider.id); setForm({ name: provider.name, providerType: provider.providerType, baseUrl: provider.baseUrl, defaultModel: provider.defaultModel, timeoutSeconds: provider.timeoutSeconds, secret: "" }); setConflict(false); setError("已加载服务端最新配置，请确认后重新保存。"); } catch { setError("暂时无法加载最新配置。"); } finally { setSaving(false); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const invalid = validateProviderForm(form, secretSupported, editing); if (invalid) { setError(invalid); return; } setSaving(true); try { if (editing) await updateLlmProvider(drawer.provider.id, { name: form.name, baseUrl: form.baseUrl, defaultModel: form.defaultModel, timeoutSeconds: form.timeoutSeconds, secret: form.secret, expectedVersion: drawer.provider.version }, crypto.randomUUID()); else await createLlmProvider(form, crypto.randomUUID()); await onSaved(); onClose(); } catch (cause) { const api = cause instanceof ApiError ? cause : undefined; if (api?.status === 409 || api?.code === "version_conflict") { setConflict(true); setError("该配置已被其他操作更新，请重新加载后再保存。"); } else setError("保存失败，请检查输入后重试。"); } finally { setSaving(false); } };
  return <div className="llm-drawer-backdrop"><aside className="llm-drawer" role="dialog" aria-modal="true"><header><div><h2>{editing ? "编辑 LLM 配置" : "添加 LLM 配置"}</h2><p>配置全局 LLM 连接，供项目工作流调用</p></div><button type="button" aria-label="关闭" onClick={onClose} disabled={saving}>×</button></header><form onSubmit={submit}><div className="llm-drawer-body"><label>配置名称 *<input value={form.name} maxLength={120} onChange={event => set("name", event.target.value)} disabled={saving} /></label><label>服务类型 *<select value={form.providerType} onChange={event => set("providerType", event.target.value as LlmProviderType)} disabled={editing || saving}>{types.map(type => <option key={type.providerType} value={type.providerType}>{type.displayName}</option>)}</select>{editing && <small>服务类型创建后不可修改。</small>}</label><label>服务地址 *<input type="url" value={form.baseUrl} maxLength={512} onChange={event => set("baseUrl", event.target.value)} disabled={saving} /></label><label>默认模型 *<input value={form.defaultModel} maxLength={160} onChange={event => set("defaultModel", event.target.value)} disabled={saving} /></label>{secretSupported && <label>API Key{editing ? "" : " *"}<input type="password" value={form.secret} autoComplete="new-password" onChange={event => set("secret", event.target.value)} disabled={saving} /><small>{editing && drawer.provider.hasSecret ? "已配置；留空将保留原密钥。" : "密钥加密保存，保存后不会回显明文。"}</small></label>}<label>请求超时（秒）<input type="number" min="5" max="300" value={form.timeoutSeconds} onChange={event => set("timeoutSeconds", Number(event.target.value))} disabled={saving} /></label><div className="llm-deferred"><button type="button" disabled>验证连接（后续开放）</button><p>本迭代仅保存配置，不会连接第三方 LLM 服务。</p></div>{error && <div className="llm-form-error" role="alert">{error}{conflict && <button type="button" onClick={() => void reload()} disabled={saving}>重新加载</button>}</div>}</div><footer><button type="button" onClick={onClose} disabled={saving}>取消</button><button className="primary" disabled={saving}>{saving ? "保存中…" : "保存"}</button></footer></form></aside></div>;
}

export function SettingsPage() {
  const [providers, setProviders] = useState<LlmProviderVm[] | null>(null); const [types, setTypes] = useState<LlmProviderTypeDto[] | null>(null); const [total, setTotal] = useState(0); const [query, setQuery] = useState(""); const [providerType, setProviderType] = useState<LlmProviderType | "">(""); const [status, setStatus] = useState(""); const [enabled, setEnabled] = useState(""); const [offset, setOffset] = useState(0); const [drawer, setDrawer] = useState<Drawer>(null); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const limit = 20;
  const load = useCallback(async (signal?: AbortSignal) => { setError(undefined); try { const [result, catalogue] = await Promise.all([listLlmProviders({ q: query, providerType: providerType || undefined, integrationStatus: status === "not_connected" ? "not_connected" : undefined, enabled: enabled === "true" ? true : enabled === "false" ? false : undefined, limit, offset }, { signal }), listLlmProviderTypes({ signal })]); setProviders(result.items.map(mapLlmProvider)); setTypes(catalogue.items); setTotal(result.total); } catch (cause) { if (!(cause instanceof ApiError && cause.code === "cancelled")) setError("暂时无法加载 LLM 配置，请稍后重试。"); } }, [enabled, offset, providerType, query, status]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => void load(controller.signal), 300); return () => { window.clearTimeout(timer); controller.abort(); }; }, [load]);
  const reset = (action: () => void) => { setOffset(0); action(); }; const edit = async (provider: LlmProviderVm) => { try { setDrawer({ mode: "edit", provider: await getLlmProvider(provider.id) }); } catch { setNotice("暂时无法读取该配置详情。"); } }; const page = Math.floor(offset / limit) + 1; const pages = Math.max(1, Math.ceil(total / limit));
  return <section className="settings-content"><section className="llm-content-card"><header><div><h2>LLM 配置</h2><p>管理全局大模型连接，供项目工作流调用</p></div><button className="primary" onClick={() => setDrawer({ mode: "create" })} disabled={!types?.length}>添加 LLM 配置</button></header>{notice && <p className="llm-toast" role="status">{notice}</p>}{error ? <div className="llm-state" role="alert"><h3>暂时无法加载</h3><p>{error}</p><button onClick={() => void load()}>重试</button></div> : !providers || !types ? <div className="llm-loading" role="status">正在加载 LLM 配置…</div> : providers.length === 0 ? <div className="llm-state"><h3>暂无 LLM 配置</h3><p>添加一个 LLM 配置后，可供后续项目工作流使用。</p></div> : <><div className="llm-toolbar"><input value={query} onChange={event => reset(() => setQuery(event.target.value))} placeholder="搜索配置名称" /><select value={providerType} onChange={event => reset(() => setProviderType(event.target.value as LlmProviderType | ""))}><option value="">全部类型</option>{types.map(type => <option key={type.providerType} value={type.providerType}>{type.displayName}</option>)}</select><select value={status} onChange={event => reset(() => setStatus(event.target.value))}><option value="">全部集成状态</option><option value="not_connected">未接入</option></select><select value={enabled} onChange={event => reset(() => setEnabled(event.target.value))}><option value="">全部启用状态</option><option value="false">未启用</option><option value="true">已启用</option></select><span>共 {total} 个配置</span></div><div className="llm-table-wrap"><table><thead><tr><th>配置名称</th><th>服务类型</th><th>服务地址</th><th>默认模型</th><th>集成状态</th><th>操作</th></tr></thead><tbody>{providers.map(provider => <tr key={provider.id}><td><strong>{provider.name}</strong>{provider.hasSecret && <small>密钥已配置{provider.secretFingerprint && ` · ${provider.secretFingerprint}`}</small>}</td><td>{provider.providerTypeLabel}</td><td className="llm-url">{provider.baseUrl}</td><td>{provider.defaultModel}</td><td><span className="llm-status">{provider.integrationStatusLabel}</span></td><td><button onClick={() => void edit(provider)}>编辑</button></td></tr>)}</tbody></table></div><div className="llm-pagination"><span>第 {page} / {pages} 页</span><button disabled={offset === 0} onClick={() => setOffset(value => Math.max(0, value - limit))}>上一页</button><button disabled={offset + limit >= total} onClick={() => setOffset(value => value + limit)}>下一页</button></div></>}</section>{drawer && types && <ProviderDrawer drawer={drawer} types={types} onClose={() => setDrawer(null)} onSaved={async () => { await load(); setNotice("配置已保存，并已同步服务端最新数据。"); }} />}</section>;
}
