"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { listCapabilities, listIntegrations, type CapabilityVm, type IntegrationVm } from "./global-lite-api";

function ErrorState({error,retry}:{error:ApiError;retry:()=>void}){return <section className="lite-state"><h2>暂时无法加载</h2><p>{error.message}</p><button onClick={retry}>重试</button></section>}
function CapabilityCard({item}:{item:CapabilityVm}){return <article className="lite-card settings-card"><div><span className="lite-kind">Capability · {item.key}</span><h2>{item.label}</h2><p>{item.description}</p></div><dl className="lite-meta"><div><dt>状态</dt><dd><span className={`lite-badge ${item.enabled?"enabled":"not-configured"}`}>{item.enabled?"已启用":"暂未配置"}</span></dd></div><div><dt>enabled</dt><dd>{item.enabled?"true":"false"}</dd></div></dl>{item.workflowKeys.length?<Link className="lite-inline-link" href="/workflows">查看内置流程</Link>:<p className="lite-readonly">P0 不提供真实 AI 配置、密钥或 Provider 设置。</p>}</article>}
function IntegrationCard({item}:{item:IntegrationVm}){return <article className="lite-card settings-card"><div><span className="lite-kind">{item.category === "publish" ? "发布平台" : "外部工作流"}</span><h2>{item.label}</h2><p>{item.description}</p></div><dl className="lite-meta"><div><dt>状态</dt><dd><span className="lite-badge unavailable">暂未开放</span></dd></div><div><dt>available</dt><dd>{item.available?"true":"false"}</dd></div></dl><p className="lite-readonly">只读状态；不提供连接、授权或配置操作。</p></article>}
export function SettingsPage(){const [capabilities,setCapabilities]=useState<CapabilityVm[]|null>(null);const [integrations,setIntegrations]=useState<IntegrationVm[]|null>(null);const [error,setError]=useState<ApiError|null>(null);const load=useCallback(()=>{setCapabilities(null);setIntegrations(null);setError(null);void Promise.all([listCapabilities(),listIntegrations()]).then(([capabilityResult,integrationResult])=>{setCapabilities(capabilityResult);setIntegrations(integrationResult);}).catch((cause:ApiError)=>setError(cause));},[]);useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer);},[load]);return <main className="lite-main"><header><h1>设置</h1><p>查看全局内容能力与外部集成的只读状态。</p></header><p className="lite-notice">P0 仅展示冻结描述符，不展示凭据、连接串或内部配置，也不提供保存、测试连接和重新授权。</p>{error?<ErrorState error={error} retry={load}/>:!capabilities||!integrations?<div className="lite-loading">正在加载设置状态…</div>:<><section><div className="lite-section-heading"><h2>内容能力状态</h2></div>{capabilities.length?<div className="lite-grid">{capabilities.map(item=><CapabilityCard key={item.key} item={item}/>)}</div>:<section className="lite-state"><h2>暂无能力状态</h2><p>当前没有可展示的 Capability。</p></section>}</section><section className="settings-integrations"><div className="lite-section-heading"><div><h2>外部集成</h2><p>发布与工作流集成均保持只读、暂未开放状态。</p></div></div>{integrations.length?<div className="lite-grid">{integrations.map(item=><IntegrationCard key={item.key} item={item}/>)}</div>:<section className="lite-state"><h2>暂无集成状态</h2><p>当前没有可展示的 Integration。</p></section>}</section></>}</main>}
