"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { listBuiltinWorkflows, listGlobalWorkflowRuns, type BuiltinWorkflowVm, type GlobalWorkflowRunDto, type WorkflowRunVm } from "./global-lite-api";
const limit = 2;
const statusLabel: Record<GlobalWorkflowRunDto["status"], string> = { running: "运行中", succeeded: "已成功", failed: "失败" };
const date = (value: string | null) => value ? new Date(value).toLocaleString("zh-CN", { dateStyle: "short", timeStyle: "short" }) : "进行中";
function ErrorState({ error, retry }: { error: ApiError; retry: () => void }) { return <section className="lite-state"><h2>暂时无法加载</h2><p>{error.message}</p><button onClick={retry}>重试</button></section>; }
function WorkflowCard({ item }: { item: BuiltinWorkflowVm }) { return <article className="lite-card workflow-card"><span className="lite-kind">内置 · 模拟能力</span><h2>{item.label}</h2><p>{item.description}</p><dl className="lite-meta"><div><dt>workflow_key</dt><dd>{item.key}</dd></div><div><dt>provider</dt><dd>{item.provider}</dd></div><div><dt>结果类型</dt><dd>{item.resultKind}</dd></div><div><dt>状态</dt><dd><span className="lite-badge enabled">已启用</span></dd></div></dl></article>; }
function RunRow({ item }: { item: WorkflowRunVm }) { return <article className="workflow-run"><div className="workflow-run-heading"><div><span className={`lite-badge ${item.status}`}>{statusLabel[item.status]}</span><h3>{item.workflowKey}</h3><p>{item.provider} · {item.projectName}</p></div>{item.projectWorksHref && <Link href={item.projectWorksHref}>打开项目作品</Link>}</div><dl><div><dt>内容对象</dt><dd>{item.subject}</dd></div><div><dt>开始时间</dt><dd>{date(item.startedAt)}</dd></div><div><dt>结束时间</dt><dd>{date(item.finishedAt)}</dd></div></dl>{item.failureSummary && <p className="workflow-failure">失败摘要：{item.failureSummary}</p>}</article>; }
export function WorkflowsPage() {
  const [builtin, setBuiltin] = useState<BuiltinWorkflowVm[] | null>(null); const [runs, setRuns] = useState<{ items: WorkflowRunVm[]; total: number } | null>(null); const [error, setError] = useState<ApiError | null>(null); const [offset, setOffset] = useState(0);
  const load = useCallback(async (signal?: AbortSignal) => { setBuiltin(null); setRuns(null); setError(null); try { const [builtinResult, runsResult] = await Promise.all([listBuiltinWorkflows({ signal }), listGlobalWorkflowRuns({ limit, offset }, { signal })]); setBuiltin(builtinResult); setRuns(runsResult); } catch (cause) { if (!(cause instanceof ApiError && cause.code === "cancelled")) setError(cause instanceof ApiError ? cause : new ApiError("Unable to load workflows.", 0)); } }, [offset]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => void load(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort(); }; }, [load]);
  const total = runs?.total ?? 0; const page = Math.floor(offset / limit) + 1; const pages = Math.max(1, Math.ceil(total / limit));
  return <main className="lite-main"><header><h1>流程</h1><p>查看内置模拟流程及跨项目的只读执行记录。</p></header><p className="lite-notice">此页面只展示内置 mock 流程状态，不提供编辑、编排、执行或外部工作流连接。</p>{error ? <ErrorState error={error} retry={() => void load()} /> : !builtin || !runs ? <div className="lite-loading">正在加载流程中心…</div> : <><section><div className="lite-section-heading"><h2>内置 Workflow Lite</h2><span>{builtin.length} 项能力</span></div>{builtin.length ? <div className="lite-grid">{builtin.map((item) => <WorkflowCard key={item.key} item={item} />)}</div> : <section className="lite-state"><h2>暂无内置流程</h2><p>当前没有可展示的内置模拟流程。</p></section>}</section><section className="workflow-runs"><div className="lite-section-heading"><div><h2>全局执行记录</h2><p>按开始时间倒序展示；失败记录只提供安全摘要。</p></div><span>{total} 条</span></div>{runs.items.length ? <><div className="workflow-run-list">{runs.items.map((item) => <RunRow key={item.id} item={item} />)}</div><footer className="lite-pager"><span>第 {page} / {pages} 页</span><button disabled={!offset} onClick={() => setOffset(Math.max(0, offset - limit))}>上一页</button><button disabled={offset + limit >= total} onClick={() => setOffset(offset + limit)}>下一页</button></footer></> : <section className="lite-state"><h2>暂无执行记录</h2><p>当前没有可展示的 WorkflowRun。</p></section>}</section></>}</main>;
}
