"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {ApiError,listProjectWorks,type ProjectWorkListDto} from "./project-work-api";
import {projectWorksRoutes,toProjectWorkView,type ProjectWorkView} from "./project-work-presentation";

const limit=20;
export function ProjectWorksWorkspace({projectId}:{projectId:string}) { const [data,setData]=useState<ProjectWorkListDto|null>(null),[error,setError]=useState<ApiError|null>(null),[offset,setOffset]=useState(0),[selected,setSelected]=useState<string|null>(null),[reload,setReload]=useState(0);useEffect(()=>{const controller=new AbortController();setData(null);setError(null);void listProjectWorks(projectId,{limit,offset,signal:controller.signal}).then(result=>{setData(result);setSelected(current=>current&&result.items.some(x=>x.work_id===current)?current:result.items[0]?.work_id??null);}).catch(cause=>{if(!controller.signal.aborted)setError(cause as ApiError);});return()=>controller.abort();},[offset,projectId,reload]); const works=useMemo(()=>data?.items.map(toProjectWorkView)??[],[data]);const selectedWork=works.find(x=>x.work_id===selected)??works[0];const retry=useCallback(()=>setReload(x=>x+1),[]); const page=data?Math.floor(data.offset/data.limit)+1:1,pages=data?Math.max(1,Math.ceil(data.total/data.limit)):1;
 if(!data&&!error) return <WorksState kind="loading"/>; if(error) return <WorksState kind={error.status===404?"not-found":"error"} retry={retry}/>; if(!data||data.total===0) return <WorksState kind="empty" workspace={`/projects/${projectId}`}/>;
 return <main className="project-works" aria-live="polite"><p className="project-works-intro">查看项目中已保存的章节正文、版本和审核结果。</p><section className="project-works-summary" aria-label="作品统计"><Stat label="章节作品" value={data.total}/><Stat label="正文版本" value={works.reduce((sum,x)=>sum+x.version_count,0)}/><Stat label="待审核" value={works.filter(x=>x.reviewLabel==="待审核").length} warning/><Stat label="已完成" value={works.filter(x=>x.latest_workflow_run?.status==="succeeded").length}/></section><div className="project-works-grid"><section className="project-works-list"><header><h1>章节列表</h1><Link href={`/projects/${projectId}/chapter-plans`} aria-label="返回章节规划">返回</Link></header><div>{works.map(work=><button type="button" className={`project-work-card ${selectedWork?.work_id===work.work_id?"selected":""}`} key={work.work_id} onClick={()=>setSelected(work.work_id)} aria-pressed={selectedWork?.work_id===work.work_id}><span className={`project-work-badge ${work.reviewLabel}`}>{work.reviewLabel}</span><strong>{work.chapterLabel}</strong><span>当前版本：v{work.current_version.version_no}</span><span>版本数量：{work.version_count}</span><span>当前来源：{sourceLabel(work.current_version.source)}</span></button>)}</div><footer className="project-works-pagination"><span>共 {data.total} 条记录</span><div><button disabled={page===1} onClick={()=>setOffset(Math.max(0,offset-limit))}>上一页</button><b>{page} / {pages}</b><button disabled={page===pages} onClick={()=>setOffset(offset+limit)}>下一页</button></div></footer></section>{selectedWork&&<WorkDetail projectId={projectId} work={selectedWork}/>}</div></main> }
function Stat({label,value,warning=false}:{label:string;value:number;warning?:boolean}){return <article className={warning?"warning":""}><span>{label}</span><strong>{value}</strong></article>}
function WorkDetail({projectId,work}:{projectId:string;work:ProjectWorkView}) {const routes=projectWorksRoutes(projectId,work);return <section className="project-work-detail"><div className="project-work-detail-head"><div><h2>{work.chapterLabel}</h2><dl><div><dt>当前版本：</dt><dd>v{work.current_version.version_no}</dd></div><div><dt>当前状态：</dt><dd>{work.reviewLabel}</dd></div><div><dt>字数：</dt><dd>{work.current_version.word_count.toLocaleString()} 字</dd></div><div><dt>最近运行：</dt><dd>{work.runLabel}</dd></div></dl></div><div className="project-work-actions"><Link href={routes.editor}>打开正文</Link>{routes.review?<Link href={routes.review}>查看审核</Link>:<span aria-disabled="true">暂无审核</span>}{routes.rewrite?<Link href={routes.rewrite}>创建重写版本</Link>:<span aria-disabled="true">暂不可重写</span>}</div></div><section className="project-work-history"><h3>版本历史</h3><article className="current-version"><b>v{work.current_version.version_no}</b><span>{work.reviewLabel}</span><em>{work.current_version.is_current?"当前版本":"历史版本"}</em><p>来源：{sourceLabel(work.current_version.source)} · {work.current_version.word_count.toLocaleString()} 字</p><Link href={routes.editor}>查看</Link></article></section><section className="project-work-artifacts"><h3>交付资产 (Saved Artifacts)</h3><ul><li>章节规划</li><li>正文 v{work.current_version.version_no}</li><li>审核结果</li><li>{work.latest_workflow_run?work.runLabel:"暂无重写记录"}</li></ul></section></section>}
function WorksState({kind,retry,workspace}:{kind:"loading"|"empty"|"error"|"not-found";retry?:()=>void;workspace?:string}) {const text={loading:["正在加载作品","正在读取项目作品和版本信息。"],empty:["暂无项目作品","项目中尚未保存章节正文。"],error:["作品列表加载失败","请检查网络后重试。"],"not-found":["项目不存在或无权限","请确认项目仍存在，或返回项目工作区。"]}[kind];return <main className={`project-works-state ${kind}`} aria-busy={kind==="loading"}><h1>{text[0]}</h1><p role={kind==="error"||kind==="not-found"?"alert":undefined}>{text[1]}</p>{retry&&<button onClick={retry}>重试</button>}{workspace&&<Link href={workspace}>返回项目工作区</Link>}</main>}
function sourceLabel(source:ProjectWorkView["current_version"]["source"]){return source==="manual_created"?"人工创建":source==="mock_rewrite"?"模拟重写":"模拟生成"}
