import { ApiError, apiRequest } from "@/lib/api";

export type WorkflowRunStatus = "running" | "succeeded" | "failed";
export type RewriteFocus = "pacing" | "foreshadowing" | "character_consistency" | "world_consistency";

export interface ReviewSummaryDto { id:string; status:"completed"; conclusion:"pass"|"revise"; score:number; summary:string; created_at:string; }
export interface WorkflowRunSummaryDto { id:string; provider_key:"mock"; workflow_key:"content_mock_generate"|"content_mock_review"|"content_mock_rewrite"; status:WorkflowRunStatus; started_at:string; finished_at:string|null; }
export interface ContentVersionListItemDto { id:string; content_item_id:string; version_no:number; status:"editable_draft"|"frozen"; source:"manual_created"|"mock_generated"|"mock_rewrite"; title:string; word_count:number; created_at:string; frozen_at:string|null; is_current:boolean; source_content_version?:{id:string;version_no:number;title:string;source:"manual_created"|"mock_generated"|"mock_rewrite";frozen_at:string|null}|null; source_review_report?:ReviewSummaryDto|null; source_workflow_run?:WorkflowRunSummaryDto|null; }
export interface ContentVersionDto extends Omit<ContentVersionListItemDto,"is_current"|"source_content_version"|"source_review_report"|"source_workflow_run"> { version:number; content:string; summary:string; updated_at:string; }
export interface ContentVersionDetailDto { content_version:ContentVersionDto; content_item:{id:string;title:string;status:"draft"|"in_review"|"reviewed";current_version_id:string}; source_content_version:ContentVersionListItemDto["source_content_version"]; source_review_report:ReviewSummaryDto|null; rewrite_workflow_run:WorkflowRunSummaryDto|null; is_current:boolean; }
export interface ProjectWorkDto { work_id:string; project_id:string; chapter_plan:{id:string;chapter_no:number;title:string;status:"pending_confirmation"|"confirmed"}; content_item:{id:string;title:string;status:"draft"|"in_review"|"reviewed";current_version_id:string}; current_version:ContentVersionListItemDto; version_count:number; latest_review:ReviewSummaryDto|null; latest_workflow_run:WorkflowRunSummaryDto|null; navigation:{content_item_id:string;current_version_id:string;latest_review_report_id:string|null;latest_workflow_run_id:string|null;rewrite_source_version_id:string|null;rewrite_review_report_id:string|null;rewrite_target_version_id:string|null}; }
export interface ProjectWorkListDto {items:ProjectWorkDto[];total:number;limit:number;offset:number}
export interface ProjectWorkDetailDto {work:ProjectWorkDto;project:{id:string;name:string;status:"planning"|"producing"|"archived"};version_history:ContentVersionListItemDto[]}
export interface WorkflowRunDto {id:string;project_id:string;provider_key:"mock";workflow_key:"content_mock_rewrite";status:WorkflowRunStatus;source_content_item_id:string;source_content_version_id:string;target_content_version_id:string|null;source_review_report_id:string;input_summary:{source_version_no:number;review_report_id:string;parameters:{rewrite_focus:RewriteFocus[];preserve_ending:boolean;instructions:string|null}};output_summary:{target_version_no:2;target_content_version_id:string;word_count:number}|null;error:{code:string;message:string}|null;idempotency_key:string;request_fingerprint:string;started_at:string;finished_at:string|null;}
export interface MockRewriteResponseDto {content_item:{id:string;chapter_plan_id:string;title:string;status:"draft"|"in_review"|"reviewed";current_version_id:string};source_content_version:{id:string;version_no:number;version:number;title:string;word_count:number;source:"manual_created"|"mock_generated"|"mock_rewrite";frozen_at:string};source_review_report:ReviewSummaryDto & {content_item_id:string;content_version_id:string;provider_key:"mock"};target_content_version:ContentVersionDto;workflow_run:WorkflowRunDto;}

const query=(values:Record<string,string|number>)=>new URLSearchParams(Object.entries(values).map(([key,value])=>[key,String(value)])).toString();
export function listProjectWorks(projectId:string, options:{limit:number;offset:number;signal?:AbortSignal}) { return apiRequest<ProjectWorkListDto>(`/projects/${encodeURIComponent(projectId)}/works?${query({limit:options.limit,offset:options.offset})}`,{signal:options.signal}); }
export function getProjectWork(workId:string, signal?:AbortSignal) { return apiRequest<ProjectWorkDetailDto>(`/works/${encodeURIComponent(workId)}`,{signal}); }
export function listContentItemVersions(contentItemId:string, options:{limit?:number;offset?:number;signal?:AbortSignal}={}) { return apiRequest<{items:ContentVersionListItemDto[];total:number;limit:number;offset:number}>(`/content-items/${encodeURIComponent(contentItemId)}/versions?${query({limit:options.limit??20,offset:options.offset??0})}`,{signal:options.signal}); }
export function getContentVersion(versionId:string, signal?:AbortSignal) { return apiRequest<ContentVersionDetailDto>(`/content-versions/${encodeURIComponent(versionId)}`,{signal}); }
export function getWorkflowRun(workflowRunId:string, signal?:AbortSignal) { return apiRequest<WorkflowRunDto>(`/workflow-runs/${encodeURIComponent(workflowRunId)}`,{signal}); }
export function mockRewriteContentItem(contentItemId:string, input:{source_content_version_id:string;review_report_id:string;expected_version:number;parameters:{rewrite_focus:RewriteFocus[];preserve_ending:boolean;instructions:string|null}}, idempotencyKey:string, signal?:AbortSignal) { return apiRequest<MockRewriteResponseDto>(`/content-items/${encodeURIComponent(contentItemId)}/rewrites/mock`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify(input),signal}); }

export type ProjectWorksMockState="loading"|"success"|"single"|"empty"|"error"|"invalid-pagination"|"not-found"|"succeeded"|"failed"|"no-run"|"paged";
export function parseProjectWorksMockState(value:string|null):ProjectWorksMockState { return (["loading","success","single","empty","error","invalid-pagination","not-found","succeeded","failed","no-run","paged"].includes(value??"") ? value : "success") as ProjectWorksMockState; }
export { ApiError };
