import { ApiError } from "@/lib/api";

export type WorkflowRunStatus = "running" | "succeeded" | "failed";
export interface ProjectWorkDto { work_id:string; project_id:string; chapter_plan:{id:string;chapter_no:number;title:string;status:"pending_confirmation"|"confirmed"}; content_item:{id:string;title:string;status:"draft"|"in_review"|"reviewed";current_version_id:string}; current_version:{id:string;content_item_id:string;version_no:number;status:"editable_draft"|"frozen";source:"manual_created"|"mock_generated"|"mock_rewrite";title:string;word_count:number;created_at:string;frozen_at:string|null;is_current:boolean}; version_count:number; latest_review:{id:string;status:"completed";conclusion:"pass"|"revise";score:number;summary:string;created_at:string}|null; latest_workflow_run:{id:string;provider_key:"mock";workflow_key:"content_mock_generate"|"content_mock_review"|"content_mock_rewrite";status:WorkflowRunStatus;started_at:string;finished_at:string|null}|null; navigation:{content_item_id:string;current_version_id:string;latest_review_report_id:string|null;latest_workflow_run_id:string|null;rewrite_source_version_id:string|null;rewrite_review_report_id:string|null;rewrite_target_version_id:string|null} }
export interface ProjectWorkListDto {items:ProjectWorkDto[];total:number;limit:number;offset:number}
export type ProjectWorksMockState="loading"|"success"|"single"|"empty"|"error"|"invalid-pagination"|"not-found"|"succeeded"|"failed"|"no-run"|"paged";
export function parseProjectWorksMockState(value:string|null):ProjectWorksMockState { return (["loading","single","empty","error","invalid-pagination","not-found","succeeded","failed","no-run","paged"].includes(value??"") ? value : "success") as ProjectWorksMockState; }
export function listProjectWorks(projectId:string, options:{limit:number;offset:number;state:ProjectWorksMockState;signal?:AbortSignal}) { return import("./project-work-mock").then(({listMockProjectWorks}) => listMockProjectWorks(projectId, options)); }
export { ApiError };
