"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { ApiError } from "@/lib/api";
import { getReview, isRealReviewDetail, type RealReviewIssue } from "@/features/content-review/content-review-api";
import { createContentRewriteRun, getContentRewriteAvailability, preflightContentRewrite, rewriteErrorMessage, validRewriteInput, type RewriteAvailability, type RewriteOptions, type RewritePreflight } from "./rewrite-api";

type Props = { projectId: string; workId: string; reportId?: string; workflowRunId?: string };
export function RewriteWorkspace({ projectId, workId, reportId, workflowRunId }: Props) {
  const router = useRouter(); const [availability, setAvailability] = useState<RewriteAvailability | null>(null); const [issues, setIssues] = useState<RealReviewIssue[]>([]); const [selected, setSelected] = useState<string[]>([]); const [instructions, setInstructions] = useState(""); const [options, setOptions] = useState<RewriteOptions>({ strategy: "targeted_fix" }); const [preflight, setPreflight] = useState<RewritePreflight | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [checking, setChecking] = useState(false); const [creating, setCreating] = useState(false); const [drawer, setDrawer] = useState(false); const key = useRef<string | null>(null);
  const runUrl = useCallback((id: string) => `/projects/${projectId}/works/${workId}/rewrite?workflowRunId=${encodeURIComponent(id)}`, [projectId, workId]);
  const load = useCallback(async () => { if (!reportId) { setError("缺少审核结果，无法创建重写。"); setLoading(false); return; } setLoading(true); setError(null); try { const [next, detail] = await Promise.all([getContentRewriteAvailability(reportId), getReview(reportId)]); setAvailability(next); if (isRealReviewDetail(detail)) { const ordered = [...detail.issues].sort((a,b) => a.position - b.position || a.id.localeCompare(b.id)); setIssues(ordered); setSelected(ordered.filter(x => x.disposition === "open").slice(0,50).map(x => x.id)); } if (next.activeRun) router.replace(runUrl(next.activeRun.id)); } catch (cause) { setError(rewriteErrorMessage((cause as ApiError).code)); } finally { setLoading(false); } }, [reportId, router, runUrl]);
  useEffect(() => { void load(); }, [load]);
  const changed = () => { setPreflight(null); key.current = null; };
  const toggle = (id: string) => { const issue = issues.find(x => x.id === id); if (!issue || issue.disposition !== "open") return; setSelected(current => current.includes(id) ? current.filter(x => x !== id) : current.length >= 50 ? current : [...current, id]); changed(); };
  const runPreflight = async () => { if (!reportId) return; const invalid = validRewriteInput(selected, instructions, options); if (invalid) return setError(invalid); setChecking(true); setError(null); try { const next = await preflightContentRewrite(reportId, { selectedIssueIds: selected, optionalInstructions: instructions.trim() || null, rewriteOptions: options }); setPreflight(next); if (next.status !== "passed") setError("预检未通过，请根据检查结果修正后重试。"); } catch (cause) { setError(rewriteErrorMessage((cause as ApiError).code)); } finally { setChecking(false); } };
  const create = async () => { if (!reportId || !preflight?.preflightToken || creating) return; const submitKey = key.current ?? crypto.randomUUID(); key.current = submitKey; setCreating(true); setError(null); try { const run = await createContentRewriteRun(reportId, preflight.preflightToken, submitKey); key.current = null; router.replace(runUrl(run.id)); } catch (cause) { const api = cause as ApiError; if (["rewrite_preflight_expired","rewrite_preflight_stale","rewrite_preflight_consumed"].includes(api.code)) { key.current = null; setPreflight(null); } if (api.code === "active_rewrite_run_conflict" && typeof api.details?.workflowRunId === "string") router.replace(runUrl(api.details.workflowRunId)); else setError(rewriteErrorMessage(api.code)); } finally { setCreating(false); } };
  if (workflowRunId) return <main className="rewrite-page"><section className="rewrite-state"><h1>重写任务已创建</h1><p>任务正在排队或运行中。运行状态页面将在后续任务中完善。</p><Link href={`/workflow-runs/${encodeURIComponent(workflowRunId)}`}>查看运行详情</Link></section></main>;
  if (loading) return <main className="rewrite-page"><section className="rewrite-state"><h1>正在加载重写条件</h1></section></main>;
  if (!availability) return <main className="rewrite-page"><section className="rewrite-state"><h1>暂时无法加载</h1><p role="alert">{error}</p><button onClick={() => void load()}>重试</button></section></main>;
  const unavailable = !availability.available;
  return <main className="rewrite-page"><Link className="rewrite-back" href={`/projects/${projectId}/works/${workId}/review?reportId=${encodeURIComponent(reportId ?? "")}`}>返回审核结果</Link><section className="rewrite-layout"><article className="rewrite-source"><h1>创建正文重写</h1><p>重写将固定使用本次审核对应的来源版本，不会替换当前版本。</p><dl><div><dt>来源版本</dt><dd>V{availability.sourceContentVersionSummary.versionNo} · {availability.sourceContentVersionSummary.title}</dd></div><div><dt>待处理问题</dt><dd>{availability.openIssueCount} 个</dd></div><div><dt>工作流配置</dt><dd>{availability.configurationSummary?.workflowConfigurationName ?? "未配置"}</dd></div></dl>{unavailable ? <Availability availability={availability} projectId={projectId} /> : <><h2>选择待处理问题</h2><div className="rewrite-issues">{issues.map(issue => <label key={issue.id} className={issue.disposition === "ignored" ? "disabled" : ""}><input type="checkbox" checked={selected.includes(issue.id)} disabled={issue.disposition !== "open"} onChange={() => toggle(issue.id)} /> <b>{issue.title}</b><small>{issue.disposition === "ignored" ? "已忽略，不能用于重写" : "待处理"}</small></label>)}</div></>}</article><section className="rewrite-form"><h2>重写要求</h2><label>补充要求（可选）<textarea value={instructions} maxLength={2000} onChange={e => { setInstructions(e.target.value); changed(); }} /></label><small>{[...instructions].length}/2000</small><label>重写策略<select value={options.strategy} onChange={e => { setOptions({ strategy: e.target.value as RewriteOptions["strategy"] }); changed(); }}><option value="targeted_fix">定向修复</option><option value="creative_rewrite">创意重写</option></select></label><button type="button" onClick={() => setDrawer(true)}>查看项目重写配置</button>{error && <p className="rewrite-error" role="alert">{error}</p>}{preflight ? <Preflight report={preflight} creating={creating} onCreate={() => void create()} /> : <button className="primary" type="button" disabled={unavailable || checking} onClick={() => void runPreflight()}>{checking ? "预检中…" : "进行预检"}</button>}</section></section>{drawer && <ConfigDrawer config={availability.configurationSummary} onClose={() => setDrawer(false)} />}</main>;
}
function Availability({ availability, projectId }: { availability: RewriteAvailability; projectId: string }) { const text = availability.reason === "rewrite_not_configured" ? "当前项目尚未配置重写工作流。" : availability.reason === "no_open_issues" ? "该审核结果没有待处理问题。" : availability.reason === "active_rewrite_run_conflict" ? "已有重写任务正在执行。" : "当前审核结果暂不能创建重写。"; return <div className="rewrite-note"><p>{text}</p>{availability.activeRun ? <Link href={`/workflow-runs/${encodeURIComponent(availability.activeRun.id)}`}>进入正在执行的任务</Link> : availability.reason === "rewrite_not_configured" ? <Link href={`/projects/${projectId}/settings?tab=workflow-bindings`}>前往工作流绑定配置</Link> : null}</div>; }
function Preflight({ report, creating, onCreate }: { report: RewritePreflight; creating: boolean; onCreate: () => void }) { return <section className="rewrite-preflight"><h3>预检报告</h3><p>来源版本：V{report.sourceContentVersionSummary.versionNo}；已选择 {report.selectedIssueSummary.total} 个问题。</p><ul>{report.checks.map(check => <li key={check.code}>{check.status === "passed" ? "通过" : "阻断"}：{check.message}</li>)}</ul>{report.status === "passed" && report.preflightToken ? <button className="primary" type="button" disabled={creating} onClick={onCreate}>{creating ? "创建中…" : "确认创建重写任务"}</button> : null}</section>; }
function ConfigDrawer({ config, onClose }: { config: RewriteAvailability["configurationSummary"]; onClose: () => void }) { return <div className="rewrite-drawer-backdrop"><aside className="rewrite-drawer" role="dialog" aria-modal="true" aria-label="项目重写配置"><h2>项目重写配置</h2><p>配置由项目工作流绑定管理，仅供查看。</p><dl><div><dt>工作流</dt><dd>{config?.workflowConfigurationName ?? "未配置"}</dd></div><div><dt>输入契约</dt><dd>{config?.inputContract ?? "—"}</dd></div><div><dt>输出契约</dt><dd>{config?.outputContract ?? "—"}</dd></div></dl><button type="button" onClick={onClose}>关闭</button></aside></div>; }
