export type RewriteFocus="pacing"|"foreshadowing"|"character_consistency"|"world_consistency";
export type RewriteMockState="default"|"loading"|"success"|"invalid-parameters"|"stale"|"idempotency-conflict"|"already-exists"|"source-not-frozen"|"review-not-completed"|"relation-mismatch"|"provider-failure"|"internal-error";
export type RewriteForm={rewrite_focus:RewriteFocus[];instructions:string;preserve_ending:boolean;expected_version:number};
export type RewriteContext={projectId:string;workId:string;contentItemId:string;versionId:string;sourceVersionId:string;reviewReportId:string};
export type RewriteResult={source_content_version_id:string;target_content_version_id:string;target_version_no:2;source:"mock_rewrite";current_version_id_unchanged:true;workflow_run:{id:string;status:"succeeded";target_content_version_id:string};idempotent_replay:boolean};
export const parseRewriteState=(value:string|null):RewriteMockState=>(["loading","success","invalid-parameters","stale","idempotency-conflict","already-exists","source-not-frozen","review-not-completed","relation-mismatch","provider-failure","internal-error"].includes(value??"")?value:"default") as RewriteMockState;
export function validateRewriteForm(form:RewriteForm){const errors:{rewrite_focus?:string;instructions?:string}={};if(!form.rewrite_focus.length)errors.rewrite_focus="至少选择一项重写重点。";if(form.instructions.length>2000)errors.instructions="补充说明不能超过 2000 个字符。";return errors;}
export function createMockRewrite(context:RewriteContext,form:RewriteForm,key:string,state:RewriteMockState){return import("./rewrite-mock").then(({mockRewrite})=>mockRewrite(context,form,key,state));}
export function d5Url(context:RewriteContext,result:RewriteResult){const q=new URLSearchParams({projectId:context.projectId,workId:context.workId,contentItemId:context.contentItemId,sourceVersionId:context.sourceVersionId,targetVersionId:result.target_content_version_id,workflowRunId:result.workflow_run.id});return `/projects/${context.projectId}/works/${context.workId}/rewrite-result?${q}`;}
