import {mockRewriteContentItem,type MockRewriteResponseDto,type RewriteFocus} from "./project-work-api";
export type {RewriteFocus};
export type RewriteMockState="default"|"loading"|"success"|"invalid-parameters"|"stale"|"idempotency-conflict"|"already-exists"|"source-not-frozen"|"review-not-completed"|"relation-mismatch"|"provider-failure"|"internal-error";
export type RewriteForm={rewrite_focus:RewriteFocus[];instructions:string;preserve_ending:boolean;expected_version:number};
export type RewriteContext={projectId:string;workId:string;contentItemId:string;sourceVersionId:string;reviewReportId:string};
export type RewriteResult={source_content_version_id:string;target_content_version_id:string;target_version_no:2;source:"mock_rewrite";current_version_id_unchanged:true;workflow_run:{id:string;status:"succeeded";target_content_version_id:string};idempotent_replay:boolean};
export const parseRewriteState=(value:string|null):RewriteMockState=>(["loading","success","invalid-parameters","stale","idempotency-conflict","already-exists","source-not-frozen","review-not-completed","relation-mismatch","provider-failure","internal-error"].includes(value??"")?value:"default") as RewriteMockState;
export function validateRewriteForm(form:RewriteForm){const errors:{rewrite_focus?:string;instructions?:string}={};if(!form.rewrite_focus.length)errors.rewrite_focus="至少选择一项重写重点。";if(form.instructions.length>2000)errors.instructions="补充说明不能超过 2000 个字符。";return errors;}
export function createMockRewrite(context:RewriteContext,form:RewriteForm,key:string,signal?:AbortSignal):Promise<MockRewriteResponseDto>{return mockRewriteContentItem(context.contentItemId,{source_content_version_id:context.sourceVersionId,review_report_id:context.reviewReportId,expected_version:form.expected_version,parameters:{rewrite_focus:form.rewrite_focus,preserve_ending:form.preserve_ending,instructions:form.instructions.trim()||null}},key,signal);}
export function d5Url(context:RewriteContext,result:MockRewriteResponseDto){const q=new URLSearchParams({contentItemId:context.contentItemId,sourceVersionId:result.workflow_run.source_content_version_id,targetVersionId:result.workflow_run.target_content_version_id??result.target_content_version.id,workflowRunId:result.workflow_run.id});return `/projects/${context.projectId}/works/${context.workId}/rewrite-result?${q}`;}
export function rewriteErrorMessage(code:string){return ({invalid_request:"请求参数无效，请检查后重试。",invalid_uuid:"请求标识无效，请返回作品列表后重试。",invalid_rewrite_parameters:"重写参数无效，请检查后重试。",version_conflict:"来源版本已变化，请刷新作品后重试。",idempotency_key_reused_with_different_payload:"该提交键已用于不同请求，请修改参数后重新提交。",rewrite_already_exists:"该正文已存在重写版本。",content_version_not_frozen:"来源版本尚未冻结，不能创建重写。",review_not_completed:"来源审核尚未完成。",source_version_mismatch:"来源版本与审核结果不匹配。",cross_project_relation_conflict:"来源数据关系不匹配。",content_item_not_found:"作品不存在或无权访问。",content_version_not_found:"来源版本不存在。",review_report_not_found:"审核结果不存在。",mock_rewrite_failed:"暂时无法创建重写，请稍后使用新的提交重试。",internal_error:"暂时无法创建重写，请稍后重试。",network_error:"网络连接失败，请检查后重试。",timeout:"请求超时，请重试。"} as Record<string,string>)[code]??"暂时无法创建重写，请稍后重试。";}
