"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ApiError } from "@/lib/api";
import { cancelWorkflowRun, formatWorkflowRunJson, getWorkflowRun, listWorkflowRunEvents, retryWorkflowRun, type WorkflowRunDetailVm, type WorkflowRunEventVm } from "./workflow-run-api";
import { newIdempotencyKey } from "@/features/workflow-bindings/workflow-binding-api";

const apiError = (cause: unknown) => cause instanceof ApiError ? cause : new ApiError("暂时无法获取运行详情。", 0);
function JsonBlock({ title, value }: { title: string; value: unknown }) { return <section className="workflow-run-detail-card"><h2>{title}</h2><pre>{formatWorkflowRunJson(value)}</pre></section>; }
function Timeline({ events, error, retry }: { events: WorkflowRunEventVm[] | null; error: boolean; retry: () => void }) { if (error) return <section className="workflow-run-detail-card"><h2>事件时间线</h2><p>暂时无法获取事件记录。</p><button type="button" onClick={retry}>重新加载事件</button></section>; if (!events?.length) return <section className="workflow-run-detail-card"><h2>事件时间线</h2><p>暂无事件记录。</p></section>; return <section className="workflow-run-detail-card"><h2>事件时间线</h2><ol className="workflow-run-timeline">{events.map((event) => <li key={event.id}><div><strong>{event.title}</strong><span>{event.statusLabel} · {event.createdAtLabel}</span></div>{event.payload && <pre>{formatWorkflowRunJson(event.payload)}</pre>}</li>)}</ol></section>; }
function Confirm({ action, busy, onCancel, onConfirm }: { action: "cancel" | "retry"; busy: boolean; onCancel: () => void; onConfirm: () => void }) { const retry = action === "retry"; return <div className="workflow-run-modal" role="dialog" aria-modal="true" aria-label={retry ? "确认重试" : "确认取消"}><div><h2>{retry ? "确认重试运行" : "确认取消运行"}</h2><p>{retry ? "将复用当前运行的输入并创建新的等待执行记录。" : "取消后运行将停止，且无法恢复为执行中。"}</p><footer><button type="button" disabled={busy} onClick={onCancel}>返回</button><button type="button" disabled={busy} onClick={onConfirm}>{busy ? "提交中…" : retry ? "确认重试" : "确认取消"}</button></footer></div></div>; }
export function WorkflowRunDetailPage({ runId }: { runId: string }) {
 const [run,setRun]=useState<WorkflowRunDetailVm|null>(null),[events,setEvents]=useState<WorkflowRunEventVm[]|null>(null),[error,setError]=useState<ApiError|null>(null),[eventsError,setEventsError]=useState(false),[action,setAction]=useState<"cancel"|"retry"|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const load=useCallback(async(signal?:AbortSignal)=>{setError(null);try{const detail=await getWorkflowRun(runId,{signal});if(!signal?.aborted)setRun(detail);try{const list=await listWorkflowRunEvents(runId,{signal});if(!signal?.aborted){setEvents(list);setEventsError(false)}}catch{if(!signal?.aborted)setEventsError(true)}}catch(cause){if(!signal?.aborted)setError(apiError(cause))}},[runId]);
 useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>void load(controller.signal),0);return()=>{window.clearTimeout(timer);controller.abort()}},[load]);
 const doAction=async()=>{if(!run||!action)return;setBusy(true);setNotice("");try{const key=newIdempotencyKey();if(action==="cancel"){await cancelWorkflowRun(run.id,run.version,key);setAction(null);await load()}else{const next=await retryWorkflowRun(run.id,run.version,key);window.location.assign(`/workflow-runs/${next.id}`)}}catch(cause){const item=apiError(cause);setNotice(item.status===409?"运行状态已变化，已刷新当前详情。":"操作未完成，请刷新后重试。");setAction(null);await load()}finally{setBusy(false)}};
 if(error)return <main className="workflow-run-detail-main"><section className="workflow-run-detail-state" role="alert"><h1>无法打开运行详情</h1><p>该运行不存在或暂时无法获取。</p><button type="button" onClick={()=>void load()}>重新加载</button><Link href="/workflow-runs">返回运行记录</Link></section></main>;
 if(!run)return <main className="workflow-run-detail-main"><section className="workflow-run-detail-state" role="status"><span/><p>正在加载运行详情…</p></section></main>;
 return <main className="workflow-run-detail-main"><div className="workflow-run-detail-canvas"><Link className="workflow-run-back" href="/workflow-runs">← 返回运行记录</Link><header><div><p>流程中心 / 运行记录</p><h1>运行详情 <i className={`workflow-runs-status ${run.status}`}>{run.statusLabel}</i></h1><span>{run.stageLabel} · {run.triggerSourceLabel}</span></div><div>{run.canCancel&&<button type="button" className="workflow-run-danger" onClick={()=>setAction("cancel")}>取消运行</button>}{run.canRetry&&<button type="button" className="workflow-run-primary" onClick={()=>setAction("retry")}>重新运行</button>}</div></header>{notice&&<p className="workflow-run-notice" role="alert">{notice}</p>}<section className="workflow-run-detail-card"><h2>基本信息</h2><dl><div><dt>运行编号</dt><dd>{run.runNumber}</dd></div><div><dt>业务环节</dt><dd>{run.stageLabel}</dd></div><div><dt>触发来源</dt><dd>{run.triggerSourceLabel}</dd></div><div><dt>当前版本</dt><dd>v{run.version}</dd></div><div><dt>创建时间</dt><dd>{run.createdAtLabel}</dd></div><div><dt>更新时间</dt><dd>{run.updatedAtLabel}</dd></div></dl></section><div className="workflow-run-detail-grid"><JsonBlock title="输入参数" value={run.inputPayload}/><JsonBlock title="输出结果" value={run.outputPayload}/><JsonBlock title="安全错误信息" value={{ 错误编号:run.errorCode??"暂无", 错误说明:run.errorMessage??"暂无", 详情:run.errorDetails??{} }}/><JsonBlock title="配置快照" value={run.configurationSnapshot}/></div><Timeline events={events} error={eventsError} retry={()=>void listWorkflowRunEvents(runId).then(setEvents).then(()=>setEventsError(false)).catch(()=>setEventsError(true))}/></div>{action&&<Confirm action={action} busy={busy} onCancel={()=>setAction(null)} onConfirm={()=>void doAction()}/>}</main>;
}
