import type { ChapterPlan, ChapterPlanStatus } from "./chapter-plan-http-api";
import type { Foreshadowing, StorylineNode } from "@/lib/api";
import type { ProjectMaterialItem } from "@/features/planning-materials/contracts/materials";

export type ChapterPlanFilterStatus = "all" | ChapterPlanStatus | "draft_generated";
export const chapterPlanStatusLabels: Record<ChapterPlanStatus, string> = { pending_confirmation: "待确认", confirmed: "已确认" };
export function chapterPlanStatusLabel(status: string): string { return chapterPlanStatusLabels[status as ChapterPlanStatus] ?? (status === "generated" || status === "draft_generated" ? "已生成草稿" : "未知状态"); }
export function chapterPlanSourceLabel(source: string): string { return source === "mock_generated" ? "模拟生成" : "手动创建"; }
export function chapterPlanSummary(value: string | null | undefined): string { const summary = value?.trim(); if (!summary || summary.includes("???")) return "暂无章节规划摘要"; if (/\b(main|children|materials|unpaid_foreshadowings|prior_summaries)=/.test(summary)) { const pace = summary.match(/\b(slow|medium|fast) pace/)?.[1]; const label = pace === "slow" ? "慢节奏" : pace === "fast" ? "快节奏" : "中等节奏"; const includes = [["main=true", "主线"], ["children=true", "支线"], ["materials=true", "项目素材"], ["unpaid_foreshadowings=true", "未回收伏笔"], ["prior_summaries=true", "前文摘要"]].filter(([key]) => summary.includes(key)).map(([, text]) => text); return includes.length ? `${label}推进，并参考${includes.join("、")}。` : `${label}推进章节内容。`; } return summary; }
export function chapterPlanDetail(value: string | null | undefined, fallback: string): string { const detail = value?.trim(); return detail && !detail.includes("???") ? detail : fallback; }
export function flattenStorylines(nodes: StorylineNode[]): StorylineNode[] { return nodes.flatMap((node) => [node, ...flattenStorylines(node.children)]); }
export function createRelationNames(storylines: StorylineNode[], materials: ProjectMaterialItem[], foreshadowings: Foreshadowing[]) { return { storylines: new Map(flattenStorylines(storylines).map((item) => [item.id, item.name])), materials: new Map(materials.map((item) => [item.material.id, item.material.name])), foreshadowings: new Map(foreshadowings.map((item) => [item.id, item.title])) }; }
export function relationValues(ids: string[], names: Map<string, string>, empty: string): string[] { const values = ids.map((id) => names.get(id)).filter((value): value is string => Boolean(value)); return values.length ? values : [empty]; }
export function createChapterPlanStats(plans: ChapterPlan[]) { return { all: plans.length, pending: plans.filter((plan) => plan.status === "pending_confirmation").length, confirmed: plans.filter((plan) => plan.status === "confirmed").length, draftGenerated: plans.filter((plan) => (plan.status as string) === "generated" || (plan.status as string) === "draft_generated").length }; }
