package contentitem

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/local/ai-content-factory/apps/api/internal/chapterplan"
	"github.com/local/ai-content-factory/apps/api/internal/globalconfig"
	"github.com/local/ai-content-factory/apps/api/internal/workflowbinding"
	"github.com/local/ai-content-factory/apps/api/internal/workflowrun"
)

var (
	ErrGenerationNotConfigured = errors.New("content generation workflow is not configured")
	ErrGenerationActiveRun = errors.New("content generation run is already active")
	ErrGenerationInputChanged = errors.New("content generation preflight input changed")
	ErrGenerationTokenInvalid = errors.New("content generation preflight token is invalid")
	ErrGenerationTokenExpired = errors.New("content generation preflight token expired")
)

type GenerationContextOptions struct { IncludePriorChapterSummaries, IncludeProjectMaterials, IncludeStoryContext, IncludeForeshadowings bool }
type GenerationPreflightRequest struct { ExpectedCurrentVersionID uuid.UUID; ExpectedCurrentVersion int; ContextOptions GenerationContextOptions; AdditionalInstructions *string; ActorID string }
type GenerationCheck struct { Code, Status, Message string }
type GenerationWorkflowSummary struct { ID uuid.UUID; Name, InputContractVersion, OutputContractVersion string; Version int }
type GenerationPreflightResult struct { Passed bool; Token string; ExpiresAt time.Time; SourceVersion ContentVersion; TargetVersionNo int; Workflow *GenerationWorkflowSummary; Checks []GenerationCheck }
type GenerationAllowedActions struct { CanPreflight, CanStartGeneration, CanCancelRuntime, CanRetryRuntime, CanRetryResultConsumption, CanViewCandidate, CanSetCandidateCurrent bool }
type GenerationSummary struct { Detail Detail; WorkflowConfigured bool; State string; ActiveRun, LatestRun *workflowrun.WorkflowRun; LatestEvents []workflowrun.Event; LatestCandidate *ContentVersion; LatestError *GenerationSafeError; CanGenerate, CandidateCanBecomeCurrent bool; AllowedActions GenerationAllowedActions }
type GenerationSafeError struct { Code, Message string; Details map[string]any }

type GenerationService struct { repo *PostgresRepository; bindings interface{ GetByProjectAndStage(context.Context, uuid.UUID, workflowbinding.WorkflowBindingStage) (workflowbinding.ProjectWorkflowBinding, error) }; configs interface{ GetWorkflow(context.Context, uuid.UUID) (globalconfig.Workflow, error); GetConnection(context.Context, uuid.UUID) (globalconfig.Connection, error) }; runs interface { CreateRunIdempotentForScope(context.Context, string, uuid.UUID, string, string, workflowrun.CreateRunPreparation) (workflowrun.WorkflowRun, error); ListRuns(context.Context, workflowrun.ListRunsQuery) (workflowrun.RunList, error); ListRunEvents(context.Context, uuid.UUID) ([]workflowrun.Event, error) }; secret []byte; now func() time.Time }

func NewGenerationService(repo *PostgresRepository, bindings interface{ GetByProjectAndStage(context.Context, uuid.UUID, workflowbinding.WorkflowBindingStage) (workflowbinding.ProjectWorkflowBinding, error) }, configs interface{ GetWorkflow(context.Context, uuid.UUID) (globalconfig.Workflow, error); GetConnection(context.Context, uuid.UUID) (globalconfig.Connection, error) }, runs interface { CreateRunIdempotentForScope(context.Context, string, uuid.UUID, string, string, workflowrun.CreateRunPreparation) (workflowrun.WorkflowRun, error); ListRuns(context.Context, workflowrun.ListRunsQuery) (workflowrun.RunList, error); ListRunEvents(context.Context, uuid.UUID) ([]workflowrun.Event, error) }, secret string) *GenerationService { return &GenerationService{repo: repo, bindings: bindings, configs: configs, runs: runs, secret: []byte(secret), now: time.Now} }

func generationDigest(item Detail, request GenerationPreflightRequest, binding workflowbinding.ProjectWorkflowBinding, workflow globalconfig.Workflow) string { raw, _ := json.Marshal(struct { ItemID, VersionID uuid.UUID; Version, ItemVersion int; Context GenerationContextOptions; Instructions *string; BindingID uuid.UUID; BindingVersion int; WorkflowID uuid.UUID; WorkflowVersion int }{item.Item.ID, item.CurrentVersion.ID, item.CurrentVersion.Version, item.Item.Version, request.ContextOptions, request.AdditionalInstructions, binding.ID, binding.Version, workflow.ID, workflow.Version}); sum := sha256.Sum256(raw); return hex.EncodeToString(sum[:]) }
func (s *GenerationService) runnable(ctx context.Context, projectID uuid.UUID) (workflowbinding.ProjectWorkflowBinding, globalconfig.Workflow, error) { binding, err := s.bindings.GetByProjectAndStage(ctx, projectID, workflowbinding.StageContentGeneration); if err != nil { return workflowbinding.ProjectWorkflowBinding{}, globalconfig.Workflow{}, ErrGenerationNotConfigured }; workflow, err := s.configs.GetWorkflow(ctx, binding.WorkflowConfigurationID); if err != nil || !workflow.Enabled { return binding, globalconfig.Workflow{}, ErrGenerationNotConfigured }; connection, err := s.configs.GetConnection(ctx, workflow.ConnectionID); if err != nil || !connection.Enabled || connection.IntegrationStatus != "connected" { return binding, workflow, ErrGenerationNotConfigured }; return binding, workflow, nil }
func (s *GenerationService) active(ctx context.Context, item Detail) (*workflowrun.WorkflowRun, error) { kind := "content_item"; list, err := s.runs.ListRuns(ctx, workflowrun.ListRunsQuery{ListFilter: workflowrun.ListFilter{ProjectID: &item.Item.ProjectID, Stage: "content_generation", SubjectType: &kind, SubjectID: &item.Item.ID, Limit: 20}}); if err != nil { return nil, err }; for i := range list.Items { if list.Items[i].Status == workflowrun.StatusQueued || list.Items[i].Status == workflowrun.StatusRunning { return &list.Items[i], nil } }; return nil, nil }
func validGenerationInput(r GenerationPreflightRequest) bool { return r.ExpectedCurrentVersionID != uuid.Nil && r.ExpectedCurrentVersion >= 1 && strings.TrimSpace(r.ActorID) != "" && (r.AdditionalInstructions == nil || len([]rune(strings.TrimSpace(*r.AdditionalInstructions))) <= 2000) }
func (s *GenerationService) Preflight(ctx context.Context, itemID uuid.UUID, request GenerationPreflightRequest) (GenerationPreflightResult, error) {
	if !validGenerationInput(request) { return GenerationPreflightResult{}, ErrValidation }
	detail, err := s.repo.GetByID(ctx, itemID); if err != nil { return GenerationPreflightResult{}, err }
	result := GenerationPreflightResult{SourceVersion: detail.CurrentVersion, TargetVersionNo: detail.CurrentVersion.VersionNo+1}
	checks := func(code, status, message string) { result.Checks = append(result.Checks, GenerationCheck{code,status,message}) }
	var chapterStatus string; if err = s.repo.db.QueryRow(ctx, "SELECT status FROM chapter_plans WHERE id=$1 AND project_id=$2", detail.Item.ChapterPlanID, detail.Item.ProjectID).Scan(&chapterStatus); err != nil || chapterStatus != "confirmed" { checks("chapter_plan_confirmed","blocked","章节计划尚未确认"); return result, nil }; checks("chapter_plan_confirmed","passed","章节计划已确认")
	if detail.CurrentVersion.ID != request.ExpectedCurrentVersionID || detail.CurrentVersion.Version != request.ExpectedCurrentVersion { checks("current_version_unchanged","blocked","当前正文版本已变化"); return result, nil }; checks("current_version_unchanged","passed","当前正文版本未变化")
	binding, workflow, err := s.runnable(ctx, detail.Item.ProjectID); if err != nil { checks("project_binding_available","blocked","尚未配置正文生成工作流"); checks("execution_integration_available","blocked","工作流执行连接不可用"); return result, nil }; result.Workflow = &GenerationWorkflowSummary{workflow.ID,workflow.Name,workflow.InputContractVersion,workflow.OutputContractVersion,workflow.Version}; checks("project_binding_available","passed","项目工作流绑定可用"); checks("execution_integration_available","passed","工作流执行连接可用")
	active, err := s.active(ctx, detail); if err != nil { return result, err }; if active != nil { checks("active_run_absent","blocked","当前正文已有运行中的生成任务"); return result, nil }; checks("active_run_absent","passed","当前正文没有活跃生成任务")
	checks("generation_input_valid","passed","生成输入有效")
	contextOptions, _ := json.Marshal(request.ContextOptions); digest := generationDigest(detail, request, binding, workflow); now := s.now().UTC(); claims := chapterplan.PreflightTokenClaims{ProjectID: detail.Item.ProjectID, ActorID: request.ActorID, Stage: "content_generation", ContextOptions: contextOptions, AdditionalInstructions: request.AdditionalInstructions, InputDigest: digest, BindingID: binding.ID, BindingVersion: binding.Version, IssuedAt: now.Unix(), ExpiresAt: now.Add(10*time.Minute).Unix(), Nonce: uuid.NewString()}; token, err := chapterplan.SignPreflightToken(s.secret, claims); if err != nil { return result, err }; result.Passed, result.Token, result.ExpiresAt = true, token, time.Unix(claims.ExpiresAt,0).UTC(); return result, nil
}
func (s *GenerationService) CreateRun(ctx context.Context, itemID uuid.UUID, actorID, token, key string) (workflowrun.WorkflowRun, error) {
	claims, err := chapterplan.VerifyPreflightToken(s.secret, token, s.now()); if errors.Is(err, chapterplan.ErrPreflightTokenExpired) { return workflowrun.WorkflowRun{}, ErrGenerationTokenExpired }; if err != nil || claims.Stage != "content_generation" { return workflowrun.WorkflowRun{}, ErrGenerationTokenInvalid }
	hash := workflowrun.Fingerprint(struct { ItemID uuid.UUID; TokenDigest string }{itemID, claims.InputDigest})
	return s.runs.CreateRunIdempotentForScope(ctx, "createContentGenerationRun", claims.ProjectID, key, hash, func() (workflowrun.CreateRunCommand, error) { request := GenerationPreflightRequest{ExpectedCurrentVersionID: uuid.Nil, ActorID: actorID}; if json.Unmarshal(claims.ContextOptions,&request.ContextOptions)!=nil{return workflowrun.CreateRunCommand{},ErrGenerationTokenInvalid}; detail, e := s.repo.GetByID(ctx,itemID); if e != nil { return workflowrun.CreateRunCommand{}, e }; if detail.Item.ProjectID != claims.ProjectID || claims.ActorID != actorID { return workflowrun.CreateRunCommand{}, ErrGenerationInputChanged }; binding, workflow, e := s.runnable(ctx, detail.Item.ProjectID); if e != nil { return workflowrun.CreateRunCommand{}, e }; request.ExpectedCurrentVersionID, request.ExpectedCurrentVersion = detail.CurrentVersion.ID, detail.CurrentVersion.Version; request.AdditionalInstructions = claims.AdditionalInstructions; if generationDigest(detail,request,binding,workflow) != claims.InputDigest || binding.ID != claims.BindingID || binding.Version != claims.BindingVersion { return workflowrun.CreateRunCommand{}, ErrGenerationInputChanged }; kind := "content_item"; historical, e := s.runs.ListRuns(ctx, workflowrun.ListRunsQuery{ListFilter:workflowrun.ListFilter{ProjectID:&detail.Item.ProjectID,Stage:"content_generation",SubjectType:&kind,SubjectID:&detail.Item.ID,Limit:100}}); if e != nil{return workflowrun.CreateRunCommand{},e}; for _, prior := range historical.Items { var payload struct{ PreflightTokenNonce string `json:"preflightTokenNonce"` }; if json.Unmarshal(prior.InputPayload,&payload)==nil && payload.PreflightTokenNonce==claims.Nonce{return workflowrun.CreateRunCommand{},ErrGenerationTokenInvalid} }; if active, e := s.active(ctx, detail); e != nil { return workflowrun.CreateRunCommand{}, e } else if active != nil { return workflowrun.CreateRunCommand{}, ErrGenerationActiveRun }; subjectType, subjectID := "content_item", detail.Item.ID; payload, _ := json.Marshal(map[string]any{"stage":"content_generation","sourceContentVersionId":detail.CurrentVersion.ID,"sourceContentVersionVersion":detail.CurrentVersion.Version,"preflightTokenNonce":claims.Nonce,"additionalInstructions":claims.AdditionalInstructions,"contextOptions":claims.ContextOptions}); return workflowrun.CreateRunCommand{ProjectID:detail.Item.ProjectID,Stage:"content_generation",SubjectType:&subjectType,SubjectID:&subjectID,InputPayload:payload,TriggerSource:"manual"}, nil })
}
func (s *GenerationService) Summary(ctx context.Context, itemID uuid.UUID) (GenerationSummary, error) {
	detail, err := s.repo.GetByID(ctx,itemID); if err != nil { return GenerationSummary{}, err }; out := GenerationSummary{Detail:detail,State:"idle",LatestEvents:[]workflowrun.Event{}}; _, _, configuredErr := s.runnable(ctx,detail.Item.ProjectID); out.WorkflowConfigured = configuredErr == nil; kind := "content_item"; list, err := s.runs.ListRuns(ctx,workflowrun.ListRunsQuery{ListFilter:workflowrun.ListFilter{ProjectID:&detail.Item.ProjectID,Stage:"content_generation",SubjectType:&kind,SubjectID:&detail.Item.ID,Limit:20}}); if err != nil { return out,err }; if len(list.Items)>0 { out.LatestRun=&list.Items[0]; for i := range list.Items { if list.Items[i].Status==workflowrun.StatusQueued || list.Items[i].Status==workflowrun.StatusRunning { out.ActiveRun=&list.Items[i]; break } }; out.LatestEvents,_=s.runs.ListRunEvents(ctx,out.LatestRun.ID) }
	candidate, e := scanVersion(s.repo.db.QueryRow(ctx,"SELECT "+versionColumns+" FROM content_versions WHERE content_item_id=$1 AND source='workflow_generated' AND id<>$2 ORDER BY version_no DESC,id DESC LIMIT 1",detail.Item.ID,detail.Item.CurrentVersionID)); if e==nil { out.LatestCandidate=&candidate; out.CandidateCanBecomeCurrent=candidate.SourceContentVersionID!=nil && candidate.SourceContentVersionVersion!=nil && *candidate.SourceContentVersionID==detail.CurrentVersion.ID && *candidate.SourceContentVersionVersion==detail.CurrentVersion.Version }
	if !out.WorkflowConfigured { out.State="not_configured" } else if out.ActiveRun!=nil && out.ActiveRun.Status==workflowrun.StatusQueued { out.State="queued" } else if out.ActiveRun!=nil { out.State="running" } else if out.LatestRun!=nil { for _, event := range out.LatestEvents { if event.EventType==workflowrun.EventTypeResultConsumptionFailed { out.State="result_consumption_failed" }; if event.EventType=="output_validation_failed" { out.State="output_validation_failed" } }; if out.State=="idle" && (out.LatestRun.Status==workflowrun.StatusFailed || out.LatestRun.Status==workflowrun.StatusCancelled) { out.State="runtime_failed" } }; if out.State=="idle" && out.LatestCandidate!=nil { out.State="candidate_ready" }; out.CanGenerate=out.State=="idle"; out.AllowedActions=GenerationAllowedActions{CanPreflight:out.CanGenerate,CanStartGeneration:out.CanGenerate,CanCancelRuntime:out.ActiveRun!=nil,CanRetryRuntime:out.State=="runtime_failed"||out.State=="output_validation_failed",CanRetryResultConsumption:out.State=="result_consumption_failed",CanViewCandidate:out.LatestCandidate!=nil,CanSetCandidateCurrent:out.CandidateCanBecomeCurrent}; return out,nil
}
