package contentitem

import (
	"context"
	"errors"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/local/ai-content-factory/apps/api/internal/workflowbinding"
	"github.com/local/ai-content-factory/apps/api/internal/workflowrun"
	"github.com/jackc/pgx/v5/pgxpool"
)

type generationRunSpy struct { run workflowrun.WorkflowRun; getCalls, createRunCalls, runtimeDispatchCalls, n8nCalls int; events []workflowrun.Event; mu sync.Mutex }
func (s *generationRunSpy) CreateRunIdempotentForScope(context.Context,string,uuid.UUID,string,string,workflowrun.CreateRunPreparation)(workflowrun.WorkflowRun,error){s.mu.Lock();defer s.mu.Unlock();s.createRunCalls++;return workflowrun.WorkflowRun{},errors.New("unexpected create")}
func (s *generationRunSpy) CreateRunForPreflightToken(context.Context,uuid.UUID,string,string,workflowrun.CreateRunPreparation)(workflowrun.WorkflowRun,error){s.mu.Lock();defer s.mu.Unlock();s.createRunCalls++;return workflowrun.WorkflowRun{},errors.New("unexpected create")}
func (s *generationRunSpy) CreateRunForPreflightTokenIdempotent(context.Context,uuid.UUID,string,string,string,workflowrun.CreateRunPreparation)(workflowrun.WorkflowRun,error){s.mu.Lock();defer s.mu.Unlock();s.createRunCalls++;return workflowrun.WorkflowRun{},errors.New("unexpected create")}
func (s *generationRunSpy) ListRuns(context.Context,workflowrun.ListRunsQuery)(workflowrun.RunList,error){return workflowrun.RunList{},nil}
func (s *generationRunSpy) ListRunEvents(context.Context,uuid.UUID)([]workflowrun.Event,error){return nil,nil}
func (s *generationRunSpy) GetRun(context.Context,uuid.UUID)(workflowrun.WorkflowRun,error){s.mu.Lock();defer s.mu.Unlock();s.getCalls++;return s.run,nil}
func (s *generationRunSpy) AddEvent(_ context.Context,event workflowrun.Event)(workflowrun.Event,error){s.mu.Lock();defer s.mu.Unlock();s.events=append(s.events,event);return event,nil}
func (s *generationRunSpy) counts()(int,int,int,int){s.mu.Lock();defer s.mu.Unlock();return s.getCalls,s.createRunCalls,s.runtimeDispatchCalls,s.n8nCalls}

func generationFixture(t *testing.T)(*PostgresRepository,context.Context,fx,CreateResult,*generationRunSpy){db,ctx:=openDB(t);f:=fixture(t,ctx,db);repo:=NewPostgresRepository(db);item:=create(t,ctx,repo,f);connection,config,runID:=uuid.New(),uuid.New(),uuid.New();_,e:=db.Exec(ctx,"INSERT INTO workflow_connections(id,name,connection_type,base_url,auth_type,timeout_seconds,type_config,integration_status,enabled) VALUES($1,$2,'n8n','http://fixture','api_key',5,'{}','connected',true)",connection,"fixture-"+connection.String());if e!=nil{t.Fatal(e)};_,e=db.Exec(ctx,"INSERT INTO workflow_configurations(id,name,connection_id,applicable_stages,type_config,input_contract_version,output_contract_version,integration_status,enabled) VALUES($1,$2,$3,'[\"content_generation\"]','{}','v1','v1','connected',true)",config,"fixture-"+config.String(),connection);if e!=nil{t.Fatal(e)};t.Cleanup(func(){cleanupGenerationFixture(t,db,f,config,connection)});run:=insertSucceededGenerationRun(t,ctx,db,item,config,runID);return repo,ctx,f,item,&generationRunSpy{run:run}}

func cleanupGenerationFixture(t *testing.T,db *pgxpool.Pool,f fx,config,connection uuid.UUID){t.Helper();ctx,cancel:=context.WithTimeout(context.Background(),10*time.Second);defer cancel();tx,e:=db.Begin(ctx);if e!=nil{t.Errorf("generation fixture cleanup begin: %v",e);return};defer tx.Rollback(ctx);if _,e=tx.Exec(ctx,"UPDATE content_items AS item SET current_version_id=candidate.source_content_version_id FROM content_versions AS candidate WHERE item.current_version_id=candidate.id AND candidate.source='workflow_generated' AND (item.project_id=$1 OR item.project_id=$2)",f.project,f.other);e==nil{_,e=tx.Exec(ctx,"DELETE FROM content_versions WHERE source='workflow_generated' AND content_item_id IN (SELECT id FROM content_items WHERE project_id=$1 OR project_id=$2)",f.project,f.other)};if e==nil{_,e=tx.Exec(ctx,"DELETE FROM projects WHERE id=$1 OR id=$2",f.project,f.other)};if e==nil{_,e=tx.Exec(ctx,"DELETE FROM workflow_configurations WHERE id=$1",config)};if e==nil{_,e=tx.Exec(ctx,"DELETE FROM workflow_connections WHERE id=$1",connection)};if e==nil{e=tx.Commit(ctx)};if e!=nil{t.Errorf("generation fixture cleanup: %v",e)}}

func insertSucceededGenerationRun(t *testing.T,ctx context.Context,db *pgxpool.Pool,item CreateResult,config,runID uuid.UUID) workflowrun.WorkflowRun { t.Helper(); kind:="content_item";now:=time.Now().UTC();run:=workflowrun.WorkflowRun{ID:runID,RunNumber:"WR-"+runID.String()[:8],ProjectID:item.Detail.Item.ProjectID,Stage:"content_generation",WorkflowConfigurationID:config,TriggerSource:"manual",Status:workflowrun.StatusSucceeded,SubjectType:&kind,SubjectID:&item.Detail.Item.ID,ConfigurationSnapshot:[]byte(`{}`),InputPayload:[]byte(`{"sourceContentVersionId":"`+item.Detail.CurrentVersion.ID.String()+`","sourceContentVersionVersion":`+"1"+`}`),OutputPayload:[]byte(`{"title":"candidate","content":"generated text","summary":"generated summary","wordCount":14}`),StartedAt:&now,FinishedAt:&now,CreatedAt:now,UpdatedAt:now,Version:2};_,e:=db.Exec(ctx,"INSERT INTO workflow_run_records(id,run_number,project_id,stage,subject_type,subject_id,workflow_configuration_id,trigger_source,status,configuration_snapshot,input_payload,output_payload,started_at,finished_at,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)",run.ID,run.RunNumber,run.ProjectID,run.Stage,kind,item.Detail.Item.ID,config,run.TriggerSource,run.Status,run.ConfigurationSnapshot,run.InputPayload,run.OutputPayload,now,now,run.Version);if e!=nil{t.Fatal(e)};return run }

func generationCandidate(t *testing.T,ctx context.Context,repo *PostgresRepository,item CreateResult,runID uuid.UUID,versionNo int) ContentVersion { t.Helper();tx,e:=repo.db.Begin(ctx);if e!=nil{t.Fatal(e)};defer tx.Rollback(ctx);candidate:=ContentVersion{ID:uuid.New(),ContentItemID:item.Detail.Item.ID,VersionNo:versionNo,SourceContentVersionID:&item.Detail.CurrentVersion.ID,SourceContentVersionVersion:&item.Detail.CurrentVersion.Version,SourceWorkflowRunID:&runID,Title:"candidate-"+runID.String()[:8],Content:"generated text",WordCount:2,Source:ContentVersionSourceWorkflowGenerated,Status:ContentVersionStatusEditableDraft,Version:1};out,e:=repo.CreateContentVersion(ctx,tx,candidate);if e!=nil{t.Fatal(e)};if e=tx.Commit(ctx);e!=nil{t.Fatal(e)};return out }

func concurrent[T any](t *testing.T,call func(int)(T,error))([]T,[]error){t.Helper();start:=make(chan struct{});var wg sync.WaitGroup;out:=make([]T,2);errs:=make([]error,2);for i:=0;i<2;i++{wg.Add(1);go func(i int){defer wg.Done();<-start;out[i],errs[i]=call(i)}(i)};close(start);wg.Wait();return out,errs}

func TestGenerationRetryConsumptionConcurrent(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);svc:=NewGenerationService(repo,nil,nil,spy,"x");out,errs:=concurrent(t,func(i int)(ContentGenerationResult,error){return svc.RetryConsumption(ctx,spy.run.ID,RetryConsumptionRequest{ExpectedRunVersion:2,IdempotencyKey:"retry-concurrent-"+string(rune('a'+i))})});success:=0;var candidateID uuid.UUID;for i:=range out{if errs[i]==nil{success++;if candidateID==uuid.Nil{candidateID=out[i].CandidateVersion.ID}else if candidateID!=out[i].CandidateVersion.ID{t.Fatalf("two successful candidates: %s and %s",candidateID,out[i].CandidateVersion.ID)}}else if !errors.Is(errs[i],workflowrun.ErrVersionConflict){t.Fatalf("unexpected concurrent retry error: %v",errs[i])}};if success<1||count(t,ctx,repo.db,"SELECT count(*) FROM content_versions WHERE content_item_id=$1 AND source_workflow_run_id=$2",item.Detail.Item.ID,spy.run.ID)!=1{t.Fatalf("success=%d candidateCount=%d",success,count(t,ctx,repo.db,"SELECT count(*) FROM content_versions WHERE content_item_id=$1 AND source_workflow_run_id=$2",item.Detail.Item.ID,spy.run.ID))};var current uuid.UUID;if e:=repo.db.QueryRow(ctx,"SELECT current_version_id FROM content_items WHERE id=$1",item.Detail.Item.ID).Scan(&current);e!=nil||current!=item.Detail.CurrentVersion.ID{t.Fatalf("current=%s err=%v",current,e)};if count(t,ctx,repo.db,"SELECT count(*) FROM workflow_run_events WHERE run_id=$1 AND event_type='result_consumed'",spy.run.ID)!=1{t.Fatal("contradictory result-consumed events")}}

func TestGenerationRetryConsumptionIdempotencyConflict(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);svc:=NewGenerationService(repo,nil,nil,spy,"x");first,e:=svc.RetryConsumption(ctx,spy.run.ID,RetryConsumptionRequest{ExpectedRunVersion:2,IdempotencyKey:"retry-conflict"});if e!=nil{t.Fatal(e)};_,e=svc.RetryConsumption(ctx,spy.run.ID,RetryConsumptionRequest{ExpectedRunVersion:3,IdempotencyKey:"retry-conflict"});if !errors.Is(e,workflowrun.ErrIdempotencyConflict){t.Fatalf("conflict=%v",e)};if count(t,ctx,repo.db,"SELECT count(*) FROM content_versions WHERE content_item_id=$1 AND source_workflow_run_id=$2",item.Detail.Item.ID,spy.run.ID)!=1||first.CandidateVersion.SourceWorkflowRunID==nil{t.Fatal("idempotency conflict duplicated consumption")}}

func TestGenerationRetryConsumptionIsolation(t *testing.T){repo,ctx,_,_,spy:=generationFixture(t);svc:=NewGenerationService(repo,nil,nil,spy,"x");if _,e:=svc.RetryConsumption(ctx,spy.run.ID,RetryConsumptionRequest{ExpectedRunVersion:2,IdempotencyKey:"retry-isolation"});e!=nil{t.Fatal(e)};get,create,runtime,n8n:=spy.counts();if get==0||create!=0||runtime!=0||n8n!=0{t.Fatalf("get=%d createRun=%d runtimeDispatch=%d n8n=%d",get,create,runtime,n8n)}}

func TestGenerationSetCurrentConcurrentCAS(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);svc:=NewGenerationService(repo,nil,nil,spy,"x");candidateA:=generationCandidate(t,ctx,repo,item,spy.run.ID,2);runB:=insertSucceededGenerationRun(t,ctx,repo.db,item,spy.run.WorkflowConfigurationID,uuid.New());candidateB:=generationCandidate(t,ctx,repo,item,runB.ID,3);out,errs:=concurrent(t,func(i int)(Detail,error){candidate:=candidateA.ID;if i==1{candidate=candidateB.ID};return svc.SetCurrent(ctx,item.Detail.Item.ID,SetCurrentRequest{CandidateVersionID:candidate,ExpectedCurrentVersionID:item.Detail.CurrentVersion.ID,ExpectedCurrentVersion:item.Detail.CurrentVersion.Version,IdempotencyKey:"set-concurrent-"+string(rune('a'+i))})});success:=0;var winner uuid.UUID;for i:=range out{if errs[i]==nil{success++;winner=out[i].CurrentVersion.ID}else if !errors.Is(errs[i],ErrVersionConflict)&&!errors.Is(errs[i],ErrCandidateStale){t.Fatalf("unexpected concurrent set error: %v",errs[i])}};if success!=1||winner==uuid.Nil{t.Fatalf("success=%d winner=%s",success,winner)};detail,e:=repo.GetByID(ctx,item.Detail.Item.ID);if e!=nil||detail.Item.Version!=item.Detail.Item.Version+1||detail.Item.CurrentVersionID!=winner||detail.Item.ReviewedAt!=nil||detail.Item.Status!="draft"{t.Fatalf("detail=%+v err=%v",detail,e)};if count(t,ctx,repo.db,"SELECT count(*) FROM content_versions WHERE content_item_id=$1",item.Detail.Item.ID)!=3{t.Fatal("candidate or history disappeared")}}

func TestGenerationSetCurrentRowsAffectedZero(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);candidateA:=generationCandidate(t,ctx,repo,item,spy.run.ID,2);runB:=insertSucceededGenerationRun(t,ctx,repo.db,item,spy.run.WorkflowConfigurationID,uuid.New());candidateB:=generationCandidate(t,ctx,repo,item,runB.ID,3);tx,e:=repo.db.Begin(ctx);if e!=nil{t.Fatal(e)};tag,e:=tx.Exec(ctx,"UPDATE content_items SET current_version_id=$1,version=version+1 WHERE id=$2 AND current_version_id=$3 AND version=$4",candidateA.ID,item.Detail.Item.ID,item.Detail.CurrentVersion.ID,item.Detail.Item.Version);if e!=nil||tag.RowsAffected()!=1{t.Fatalf("winner tag=%d err=%v",tag.RowsAffected(),e)};if e=tx.Commit(ctx);e!=nil{t.Fatal(e)};tx,e=repo.db.Begin(ctx);if e!=nil{t.Fatal(e)};tag,e=tx.Exec(ctx,"UPDATE content_items SET current_version_id=$1,version=version+1 WHERE id=$2 AND current_version_id=$3 AND version=$4",candidateB.ID,item.Detail.Item.ID,item.Detail.CurrentVersion.ID,item.Detail.Item.Version);if e!=nil||tag.RowsAffected()!=0{t.Fatalf("expected zero rows, tag=%d err=%v",tag.RowsAffected(),e)};if e=setCurrentContentItemPointer(ctx,tx,item.Detail.Item.ID,candidateB.ID,item.Detail.CurrentVersion.ID,item.Detail.Item.Version);!errors.Is(e,ErrVersionConflict){t.Fatalf("zero-row CAS converted to %v",e)};if e=tx.Rollback(ctx);e!=nil{t.Fatal(e)}}

func TestGenerationSetCurrentIdempotencyConflict(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);svc:=NewGenerationService(repo,nil,nil,spy,"x");candidateA:=generationCandidate(t,ctx,repo,item,spy.run.ID,2);runB:=insertSucceededGenerationRun(t,ctx,repo.db,item,spy.run.WorkflowConfigurationID,uuid.New());candidateB:=generationCandidate(t,ctx,repo,item,runB.ID,3);first,e:=svc.SetCurrent(ctx,item.Detail.Item.ID,SetCurrentRequest{CandidateVersionID:candidateA.ID,ExpectedCurrentVersionID:item.Detail.CurrentVersion.ID,ExpectedCurrentVersion:item.Detail.CurrentVersion.Version,IdempotencyKey:"set-conflict"});if e!=nil{t.Fatal(e)};_,e=svc.SetCurrent(ctx,item.Detail.Item.ID,SetCurrentRequest{CandidateVersionID:candidateB.ID,ExpectedCurrentVersionID:item.Detail.CurrentVersion.ID,ExpectedCurrentVersion:item.Detail.CurrentVersion.Version,IdempotencyKey:"set-conflict"});if !errors.Is(e,workflowrun.ErrIdempotencyConflict){t.Fatalf("conflict=%v",e)};detail,e:=repo.GetByID(ctx,item.Detail.Item.ID);if e!=nil||detail.Item.CurrentVersionID!=first.CurrentVersion.ID||detail.Item.Version!=item.Detail.Item.Version+1{t.Fatalf("detail=%+v err=%v",detail,e)}}

func TestGenerationStaleCandidateAllowsRegenerationWithNextVersionNumber(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);stale:=generationCandidate(t,ctx,repo,item,spy.run.ID,2);if _,e:=repo.db.Exec(ctx,"UPDATE content_versions SET version=version+1 WHERE id=$1",item.Detail.CurrentVersion.ID);e!=nil{t.Fatal(e)};latest,e:=repo.GetByID(ctx,item.Detail.Item.ID);if e!=nil{t.Fatal(e)};runs:=&generationSummaryRuns{list:workflowrun.RunList{Items:[]workflowrun.WorkflowRun{spy.run}}};svc:=NewGenerationService(repo,generationSummaryBindings{err:workflowbinding.ErrNotFound},generationSummaryConfigs{},runs,"x");summary,e:=svc.Summary(ctx,item.Detail.Item.ID);if e!=nil||summary.State!="candidate_ready"||summary.CandidateCanBecomeCurrent||!summary.CanGenerate||summary.LatestCandidate==nil||summary.LatestCandidate.ID!=stale.ID{t.Fatalf("summary=%+v err=%v",summary,e)};if _,e=svc.SetCurrent(ctx,item.Detail.Item.ID,SetCurrentRequest{CandidateVersionID:stale.ID,ExpectedCurrentVersionID:latest.CurrentVersion.ID,ExpectedCurrentVersion:latest.CurrentVersion.Version,IdempotencyKey:"stale"});!errors.Is(e,ErrCandidateStale){t.Fatalf("set stale=%v",e)};runB:=insertSucceededGenerationRun(t,ctx,repo.db,item,spy.run.WorkflowConfigurationID,uuid.New());if e=svc.ConsumeSucceededRun(ctx,runB);e!=nil{t.Fatal(e)};candidate,e:=repo.GetContentVersionBySourceWorkflowRunID(ctx,runB.ID);if e!=nil||candidate.VersionNo!=3{t.Fatalf("candidate=%+v err=%v",candidate,e)}}

func TestGenerationSetCurrentIdempotencyReplayReturnsFirstResult(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);svc:=NewGenerationService(repo,nil,nil,spy,"x");candidateA:=generationCandidate(t,ctx,repo,item,spy.run.ID,2);runB:=insertSucceededGenerationRun(t,ctx,repo.db,item,spy.run.WorkflowConfigurationID,uuid.New());candidateB:=generationCandidate(t,ctx,repo,item,runB.ID,3);first,e:=svc.SetCurrent(ctx,item.Detail.Item.ID,SetCurrentRequest{CandidateVersionID:candidateA.ID,ExpectedCurrentVersionID:item.Detail.CurrentVersion.ID,ExpectedCurrentVersion:item.Detail.CurrentVersion.Version,IdempotencyKey:"key-a"});if e!=nil{t.Fatal(e)};second,e:=svc.SetCurrent(ctx,item.Detail.Item.ID,SetCurrentRequest{CandidateVersionID:candidateB.ID,ExpectedCurrentVersionID:first.CurrentVersion.ID,ExpectedCurrentVersion:first.CurrentVersion.Version,IdempotencyKey:"key-b"});if e!=nil{t.Fatal(e)};replay,e:=svc.SetCurrent(ctx,item.Detail.Item.ID,SetCurrentRequest{CandidateVersionID:candidateA.ID,ExpectedCurrentVersionID:item.Detail.CurrentVersion.ID,ExpectedCurrentVersion:item.Detail.CurrentVersion.Version,IdempotencyKey:"key-a"});if e!=nil||replay.CurrentVersion.ID!=first.CurrentVersion.ID||replay.CurrentVersion.ID==second.CurrentVersion.ID{t.Fatalf("replay=%+v first=%+v second=%+v err=%v",replay,first,second,e)}}

func TestOutputValidationConsumptionFailureLeavesNoCandidate(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);if _,e:=repo.db.Exec(ctx,"UPDATE workflow_run_records SET output_payload='{"+`"title":"","content":"bad","wordCount":1`+"}' WHERE id=$1",spy.run.ID);e!=nil{t.Fatal(e)};svc:=NewGenerationService(repo,nil,nil,spy,"x");if e:=svc.ConsumeSucceededRun(ctx,spy.run);!errors.Is(e,ErrValidation){t.Fatalf("consume=%v",e)};if count(t,ctx,repo.db,"SELECT count(*) FROM content_versions WHERE source_workflow_run_id=$1",spy.run.ID)!=0{t.Fatal("candidate persisted")};var current uuid.UUID;if e:=repo.db.QueryRow(ctx,"SELECT current_version_id FROM content_items WHERE id=$1",item.Detail.Item.ID).Scan(&current);e!=nil||current!=item.Detail.CurrentVersion.ID{t.Fatalf("current=%s err=%v",current,e)};spy.mu.Lock();defer spy.mu.Unlock();if len(spy.events)!=1||spy.events[0].EventType!="output_validation_failed"{t.Fatalf("events=%+v",spy.events)}}

func TestGenerationConsumptionRejectsChangedSourceVersion(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);if _,e:=repo.db.Exec(ctx,"UPDATE workflow_run_records SET input_payload=$1 WHERE id=$2",[]byte(`{"sourceContentVersionId":"`+item.Detail.CurrentVersion.ID.String()+`","sourceContentVersionVersion":99}`),spy.run.ID);e!=nil{t.Fatal(e)};svc:=NewGenerationService(repo,nil,nil,spy,"x");if e:=svc.ConsumeSucceededRun(ctx,spy.run);!errors.Is(e,ErrGenerationSourceInvalid){t.Fatalf("consume=%v",e)};if count(t,ctx,repo.db,"SELECT count(*) FROM content_versions WHERE source_workflow_run_id=$1",spy.run.ID)!=0{t.Fatal("candidate persisted")};spy.mu.Lock();defer spy.mu.Unlock();if len(spy.events)!=1||spy.events[0].EventType!=workflowrun.EventTypeResultConsumptionFailed{t.Fatalf("events=%+v",spy.events)}}
