package contentitem

import (
	"context"
	"errors"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/local/ai-content-factory/apps/api/internal/workflowrun"
)

type generationRunSpy struct { run workflowrun.WorkflowRun; getCalls int; mu sync.Mutex }
func (s *generationRunSpy) CreateRunIdempotentForScope(context.Context,string,uuid.UUID,string,string,workflowrun.CreateRunPreparation)(workflowrun.WorkflowRun,error){return workflowrun.WorkflowRun{},errors.New("unexpected create")}
func (s *generationRunSpy) ListRuns(context.Context,workflowrun.ListRunsQuery)(workflowrun.RunList,error){return workflowrun.RunList{},nil}
func (s *generationRunSpy) ListRunEvents(context.Context,uuid.UUID)([]workflowrun.Event,error){return nil,nil}
func (s *generationRunSpy) GetRun(context.Context,uuid.UUID)(workflowrun.WorkflowRun,error){s.mu.Lock();defer s.mu.Unlock();s.getCalls++;return s.run,nil}
func (s *generationRunSpy) AddEvent(context.Context,workflowrun.Event)(workflowrun.Event,error){return workflowrun.Event{},errors.New("unexpected event")}

func generationFixture(t *testing.T)(*PostgresRepository,context.Context,fx,CreateResult,*generationRunSpy){db,ctx:=openDB(t);f:=fixture(t,ctx,db);repo:=NewPostgresRepository(db);item:=create(t,ctx,repo,f);connection,config,runID:=uuid.New(),uuid.New(),uuid.New();_,e:=db.Exec(ctx,"INSERT INTO workflow_connections(id,name,connection_type,base_url,auth_type,timeout_seconds,type_config,integration_status,enabled) VALUES($1,$2,'n8n','http://fixture','api_key',5,'{}','connected',true)",connection,"fixture-"+connection.String());if e!=nil{t.Fatal(e)};_,e=db.Exec(ctx,"INSERT INTO workflow_configurations(id,name,connection_id,applicable_stages,type_config,input_contract_version,output_contract_version,integration_status,enabled) VALUES($1,$2,$3,'[\"content_generation\"]','{}','v1','v1','connected',true)",config,"fixture-"+config.String(),connection);if e!=nil{t.Fatal(e)};kind:="content_item";now:=time.Now().UTC();run:=workflowrun.WorkflowRun{ID:runID,RunNumber:"WR-"+runID.String()[:8],ProjectID:f.project,Stage:"content_generation",WorkflowConfigurationID:config,TriggerSource:"manual",Status:workflowrun.StatusSucceeded,SubjectType:&kind,SubjectID:&item.Detail.Item.ID,ConfigurationSnapshot:[]byte(`{}`),InputPayload:[]byte(`{"sourceContentVersionId":"`+item.Detail.CurrentVersion.ID.String()+`","sourceContentVersionVersion":1}`),OutputPayload:[]byte(`{"title":"candidate","content":"generated text","wordCount":2}`),StartedAt:&now,FinishedAt:&now,CreatedAt:now,UpdatedAt:now,Version:2};_,e=db.Exec(ctx,"INSERT INTO workflow_run_records(id,run_number,project_id,stage,subject_type,subject_id,workflow_configuration_id,trigger_source,status,configuration_snapshot,input_payload,output_payload,started_at,finished_at,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)",run.ID,run.RunNumber,run.ProjectID,run.Stage,kind,item.Detail.Item.ID,config,run.TriggerSource,run.Status,run.ConfigurationSnapshot,run.InputPayload,run.OutputPayload,now,now,run.Version);if e!=nil{t.Fatal(e)};return repo,ctx,f,item,&generationRunSpy{run:run}}

func TestGenerationRetryConsumptionCASIdempotencyAndIsolation(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);svc:=NewGenerationService(repo,nil,nil,spy,"x");first,e:=svc.RetryConsumption(ctx,spy.run.ID,RetryConsumptionRequest{ExpectedRunVersion:2,IdempotencyKey:"retry-a"});if e!=nil||first.CandidateVersion.SourceWorkflowRunID==nil||spy.getCalls!=2{t.Fatalf("first=%+v err=%v calls=%d",first,e,spy.getCalls)};again,e:=svc.RetryConsumption(ctx,spy.run.ID,RetryConsumptionRequest{ExpectedRunVersion:2,IdempotencyKey:"retry-a"});if e!=nil||again.CandidateVersion.ID!=first.CandidateVersion.ID{t.Fatal("replay created another candidate")};if _,e=svc.RetryConsumption(ctx,spy.run.ID,RetryConsumptionRequest{ExpectedRunVersion:3,IdempotencyKey:"retry-b"});!errors.Is(e,workflowrun.ErrVersionConflict){t.Fatalf("expected run CAS conflict: %v",e)};if count(t,ctx,repo.db,"SELECT count(*) FROM content_versions WHERE content_item_id=$1",item.Detail.Item.ID)!=2{t.Fatal("retry created duplicate candidate")}}
func TestGenerationSetCurrentCASStaleIdempotencyAndConcurrency(t *testing.T){repo,ctx,_,item,spy:=generationFixture(t);svc:=NewGenerationService(repo,nil,nil,spy,"x");candidate,e:=svc.RetryConsumption(ctx,spy.run.ID,RetryConsumptionRequest{ExpectedRunVersion:2,IdempotencyKey:"consume"});if e!=nil{t.Fatal(e)};req:=SetCurrentRequest{CandidateVersionID:candidate.CandidateVersion.ID,ExpectedCurrentVersionID:item.Detail.CurrentVersion.ID,ExpectedCurrentVersion:item.Detail.CurrentVersion.Version,IdempotencyKey:"set-a"};out,e:=svc.SetCurrent(ctx,item.Detail.Item.ID,req);if e!=nil||out.CurrentVersion.ID!=candidate.CandidateVersion.ID{t.Fatalf("set=%+v %v",out,e)};again,e:=svc.SetCurrent(ctx,item.Detail.Item.ID,req);if e!=nil||again.Item.Version!=out.Item.Version{t.Fatal("idempotent replay changed item")};if _,e=svc.SetCurrent(ctx,item.Detail.Item.ID,SetCurrentRequest{CandidateVersionID:candidate.CandidateVersion.ID,ExpectedCurrentVersionID:item.Detail.CurrentVersion.ID,ExpectedCurrentVersion:item.Detail.CurrentVersion.Version,IdempotencyKey:"set-b"});!errors.Is(e,ErrVersionConflict){t.Fatalf("expected stale CAS conflict: %v",e)};if count(t,ctx,repo.db,"SELECT count(*) FROM content_versions WHERE content_item_id=$1",item.Detail.Item.ID)!=2{t.Fatal("versions were not retained")}}
