"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from "react";
import { ApiError, updateStoryline, type StorylineNode, type UpdateStorylineInput } from "@/lib/api";
import { storylineStatus, storylineType } from "./storyline-presentation";
export function EditStorylineDialog({ storyline, parentName, onDone, onCancel }: { storyline: StorylineNode; parentName?: string; onDone: (id: string) => void; onCancel: () => void }) {
  const [form, setForm] = useState({ name: storyline.name, summary: storyline.summary, start: storyline.start_chapter?.toString() ?? "", end: storyline.end_chapter?.toString() ?? "", status: storyline.status, sort: storyline.sort_order.toString(), clearStart: false, clearEnd: false }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const toNumber = (value: string) => value === "" ? null : Number(value); const start = toNumber(form.start); const end = toNumber(form.end); if ((!form.clearStart && start !== null && (!Number.isInteger(start) || start < 1)) || (!form.clearEnd && end !== null && (!Number.isInteger(end) || end < 1)) || (!form.clearStart && !form.clearEnd && start !== null && end !== null && start > end)) { setError("请输入有效的章节范围。"); return; } const payload: UpdateStorylineInput = { expected_version: storyline.version }; if (form.name !== storyline.name) payload.name = form.name.trim(); if (form.summary !== storyline.summary) payload.summary = form.summary; if (form.status !== storyline.status) payload.status = form.status as StorylineNode["status"]; if (Number(form.sort) !== storyline.sort_order) payload.sort_order = Number(form.sort); if (form.clearStart) payload.start_chapter = null; else if (start !== storyline.start_chapter) payload.start_chapter = start; if (form.clearEnd) payload.end_chapter = null; else if (end !== storyline.end_chapter) payload.end_chapter = end; if (Object.keys(payload).length === 1) { setError("请先修改内容再保存。"); return; } setBusy(true); setError(""); try { onDone((await updateStoryline(storyline.id, payload)).id); } catch (reason) { setError(reason instanceof ApiError && reason.code === "version_conflict" ? "故事线已被更新，请重新加载后编辑。" : "无法保存故事线，请稍后重试。"); } finally { setBusy(false); } };
  return <div className="storyline-modal-backdrop" role="presentation"><div role="dialog" aria-modal="true" className="storyline-dialog"><form onSubmit={submit}><header><div><p className="eyebrow">故事线</p><h2>编辑{storylineType(storyline.type)}</h2><p>{storyline.type === "child" ? `父故事线：${parentName ?? "暂无"}` : "顶层故事线"}</p></div><button type="button" className="dialog-close" disabled={busy} onClick={onCancel}>关闭</button></header><div className="dialog-body"><p className="dialog-info">类型和层级关系由系统固定，无法修改。</p><label>名称<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>摘要<textarea value={form.summary} onChange={(event) => setForm({ ...form, summary: event.target.value })} /></label><div className="dialog-grid"><label>起始章节<input disabled={form.clearStart} type="number" min="1" value={form.start} onChange={(event) => setForm({ ...form, start: event.target.value })} /><span><input type="checkbox" checked={form.clearStart} onChange={(event) => setForm({ ...form, clearStart: event.target.checked })} /> 清除数值</span></label><label>结束章节<input disabled={form.clearEnd} type="number" min="1" value={form.end} onChange={(event) => setForm({ ...form, end: event.target.value })} /><span><input type="checkbox" checked={form.clearEnd} onChange={(event) => setForm({ ...form, clearEnd: event.target.checked })} /> 清除数值</span></label></div><div className="dialog-grid"><label>状态<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as any })}>{["active","completed","archived"].map(value=><option key={value} value={value}>{storylineStatus(value)}</option>)}</select></label><label>排序<input type="number" min="0" value={form.sort} onChange={(event) => setForm({ ...form, sort: event.target.value })} /></label></div>{error && <p className="dialog-error" role="alert">{error}</p>}</div><footer><button type="button" disabled={busy} onClick={onCancel}>取消</button><button disabled={busy}>{busy ? "正在保存…" : "保存故事线"}</button></footer></form></div></div>;
}
